export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED';

export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_FAILED = 'SET_PASSWORD_FAILED';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILED = 'GET_USER_DATA_FAILED';

export const SEND_REQUEST = 'SEND_REQUEST';
export const SEND_REQUEST_SUCCESS = 'SEND_REQUEST_SUCCESS';
export const SEND_REQUEST_FAILED = 'SEND_REQUEST_FAILED';

//GET ALL USERS DATA'S APIS
export const GET_ALL_REQUEST = 'GET_ALL_REQUEST';
export const GET_ALL_REQUEST_SUCCESS = 'GET_ALL_REQUEST_SUCCESS';
export const GET_ALL_REQUEST_FAILED = 'GET_ALL_REQUEST_FAILED';

//ACCEPTED DECLINE FRIEND REQUEST APIS
export const ACCEPTED_DECLINE_FRIEND_REQUEST =
  'ACCEPTED_DECLINE_FRIEND_REQUEST';
export const ACCEPTED_DECLINE_FRIEND_REQUEST_SUCCESS =
  'ACCEPTED_DECLINE_FRIEND_REQUEST_SUCCESS';
export const ACCEPTED_DECLINE_FRIEND_REQUEST_FAILED =
  'ACCEPTED_DECLINE_FRIEND_REQUEST_FAILED';

//USER DETAILS FILL UP APIS
export const SET_UPDATE_USER_DETAILS = 'SET_UPDATE_USER_DETAILS';
export const SET_UPDATE_USER_DETAILS_SUCCESS =
  'SET_UPDATE_USER_DETAILS_SUCCESS';
export const SET_UPDATE_USER_DETAILS_FAILED = 'SET_UPDATE_USER_DETAILS_FAILED';

// SET USERS ADDRESS APIS
export const SET_USER_ADDRESS = 'SET_USER_ADDRESS';
export const SET_USER_ADDRESS_SUCCESS = 'SET_USER_ADDRESS_SUCCESS';
export const SET_USER_ADDRESS_FAILED = 'SET_USER_ADDRESS_FAILED';

//ADD EDUCATION DETAILS APIS
export const EDUCATION_DETAILS = 'EDUCATION_DETAILS';
export const ADD_EDUCATION_DETAILS_SUCCESS = 'ADD_EDUCATION_DETAILS_SUCCESS';
export const ADD_EDUCATION_DETAILS_FAILED = 'ADD_EDUCATION_DETAILS_FAILED';

//PROFESSIONAL DETAILS APIS
export const PROFESSIONAL_DETAILS = 'PROFESSIONAL_DETAILS';
export const ADD_PROFESSIONAL_DETAILS_SUCCESS =
  'ADD_PROFESSIONAL_DETAILS_SUCCESS';
export const ADD_PROFESSIONAL_DETAILS_FAILED =
  'ADD_PROFESSIONAL_DETAILS_FAILED';

//ADD PROFILE PICTURE
export const ADD_PROFILE_PICTURE = 'ADD_PROFILE_PICTURE';
export const ADD_PROFILE_PICTURE_SUCCESS = 'ADD_PROFILE_PICTURE_SUCCESS';
export const ADD_PROFILE_PICTURE_FAILED = 'ADD_PROFILE_PICTURE_FAILED';

export const PARTNER_PREFERENCES_DETAILS = 'PARTNER_PREFERENCES_DETAILS';
export const PARTNER_PREFERENCES_DETAILS_SUCCESS =
  'PARTNER_PREFERENCES_DETAILS_SUCCESS';
export const PARTNER_PREFERENCES_DETAILS_FAILED =
  'PARTNER_PREFERENCES_DETAILS_FAILED';

// MY ALL FRIENDS

export const GET_ALL_FRIENDS = 'GET_ALL_FRIENDS';
export const GET_ALL_FRIENDS_SUCCESS = 'GET_ALL_FRIENDS_SUCCESS';
export const GET_ALL_FRIENDS_FAILED = 'GET_ALL_FRIENDS_FAILED';

export const GET_ALL_DECLINE_FRIENDS = 'GET_ALL_DECLINE_FRIENDS';
export const GET_ALL_DECLINE_FRIENDS_SUCCESS =
  'GET_ALL_DECLINE_FRIENDS_SUCCESS';
export const GET_ALL_DECLINE_FRIENDS_FAILED = 'GET_ALL_DECLINE_FRIENDS_FAILED';

export const GET_ALL_PAYMENT_DETAILS = 'GET_ALL_PAYMENT_DETAILS';
export const GET_ALL_PAYMENT_DETAILS_SUCCESS =
  'GET_ALL_PAYMENT_DETAILS_SUCCESS';
export const GET_ALL_PAYMENT_DETAILS_FAILED = 'GET_ALL_PAYMENT_DETAILS_FAILED';

// USER LIKE
export const USER_LIKE = 'USER_LIKE';
export const USER_LIKE_SUCCESS = 'USER_LIKE_SUCCESS';
export const USER_LIKE_FAILED = 'USER_LIKE_FAILED';

// USER DISLIKE
export const USER_DIS_LIKE = 'USER_DIS_LIKE';
export const USER_DIS_SUCCESS = 'USER_DIS_SUCCESS';
export const USER_DIS_FAILED = 'USER_DIS_FAILED';

// ADD SHORT LIST
export const ADD_SHORT_LIST = 'ADD_SHORT_LIST';
export const ADD_SHORT_LIST_SUCCESS = 'ADD_SHORT_LIST_SUCCESS';
export const ADD_SHORT_LIST_FAILED = 'ADD_SHORT_LIST_FAILED';

// // REMOVE SHORT LIST DATA
// export const REMOVE_SHORT_LIST = 'REMOVE_SHORT_LIST';
// export const REMOVE_SHORT_LIST_SUCCESS = 'REMOVE_SHORT_LIST_SUCCESS';
// export const REMOVE_SHORT_LIST_FAILED = 'REMOVE_SHORT_LIST_FAILED';

//DATA COUNTING LIST
export const DATA_COUNTING_LIST = 'DATA_COUNTING_LIST';
export const DATA_COUNTING_LIST_SUCCESS = 'DATA_COUNTING_LIST_SUCCESS';
export const DATA_COUNTING_LIST_FAILED = 'DATA_COUNTING_LIST_FAILED';

// SUCCESS STORIES LIST
export const GET_SUCCESS_STORIES = 'GET_SUCCESS_STORIES';
export const GET_SUCCESS_STORIES_SUCCESS = 'GET_SUCCESS_STORIES_SUCCESS';
export const GET_SUCCESS_STORIES_FAILED = 'GET_SUCCESS_STORIES_FAILED';

//  ALL SHORTLIST DATA
export const GET_ALL_SHORTLIST = 'GET_ALL_SHORTLIST';
export const GET_ALL_SHORTLIST_SUCCESS = 'GET_ALL_SHORTLIST_SUCCESS';
export const GET_ALL_SHORTLIST_FAILED = 'GET_ALL_SHORTLIST_FAILED';

//  ALL REQUEST SEND DATA
export const GET_ALL_REQUEST_SEND = 'GET_ALL_REQUEST_SEND';
export const GET_ALL_REQUEST_SEND_SUCCESS = 'GET_ALL_REQUEST_SEND_SUCCESS';
export const GET_ALL_REQUEST_SEND_FAILED = 'GET_ALL_REQUEST_SEND_FAILED';

// ADD DATING PARTNER REFERENCE
export const DATING_PARTNER_PREFERENCES_DETAILS =
  'DATING_PARTNER_PREFERENCES_DETAILS';
export const DATING_PARTNER_PREFERENCES_DETAILS_SUCCESS =
  'DATING_PARTNER_PREFERENCES_DETAILS_SUCCESS';
export const DATING_PARTNER_PREFERENCES_DETAILS_FAILED =
  'DATING_PARTNER_PREFERENCES_DETAILS_FAILED';

//GET PICTURE
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAILED = 'DELETE_IMAGE_FAILED';

export const CHANGE_STACK = 'CHANGE_STACK';

export const SET_LOADING = 'SET_LOADING';

export const LOGOUT_START = 'LOGOUT_START';
