import {StyleSheet} from 'react-native';
import {colors} from '../../../utils/colors';
import {fontFamily, fontSize, hp, wp} from '../../../utils/helpers';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  tittleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: wp(17),
  },
  topProfileIcon: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
    marginRight: hp(10.5),
    resizeMode: 'stretch',
    right: -7,
    marginTop: hp(2),
  },
  headerTittleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: wp(17),
  },
  editText: {
    color: colors.black,
    fontSize: fontSize(18),
    lineHeight: hp(27),
    fontFamily: fontFamily.poppins700,
  },
  arrowContainer: {
    width: hp(24),
    height: hp(24),
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    marginRight: 3,
  },
  arrowIcon: {
    width: hp(16),
    height: hp(16),
    resizeMode: 'contain',
  },
  headerSubText: {
    marginTop: hp(17),
    marginHorizontal: hp(17),
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins500,
    color: '#A2A2A2',
  },
  textColor: {
    color: colors.black,
  },
  selectedImage: {
    borderColor: '#007bff', // Add a border color to indicate selection
    borderWidth: 3,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#0F52BACC',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  checkmark: {
    color: 'white',
    fontSize: 40,
  },
  removeButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: '#00000066', // Red background
    borderRadius: 15,
    width: 14,
    height: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textInputContainer: {
    height: hp(110),
    marginTop: 10,
    paddingHorizontal: hp(17),
    textAlignVertical: 'top',
    color: colors.black,
    backgroundColor: '#F5F5F5',
  },
  flatListContainer: {
    marginHorizontal: wp(13),
    flex: 1,
  },
  contentContainerStyle: {
    padding: 10,
  },
  purposeContainer: {
    marginTop: 20,
    marginHorizontal: 17,
    flex: 1,
  },
  purposeTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // backgroundColor: 'orange',
    alignItems: 'center',
  },
  purposeText: {
    color: 'black',
    fontSize: 16,
    fontFamily: fontFamily.poppins600,
  },
  purposeSelectedContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    // marginTop: 10,
  },
  purposeSelectedContainerView: {
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  purpose: {
    color: 'black',
    marginRight: 10,
  },
  imageRenderImageAddContainer: {
    width: hp(106),
    height: hp(106),
    margin: 10,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  imageRenderAddPlus: {
    fontSize: 35,
    color: '#007bff',
  },
  renderCancelIconContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginHorizontal: wp(16),
  },
  renderImageContainer: {
    margin: 3,
    position: 'relative',
    width: hp(110),
    height: hp(106),
    borderRadius: 10,
  },
  renderImageStyle: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
    resizeMode: 'stretch',
  },
  selectedImageWaterMarkContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 123, 255, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  selectedImageAddContainer: {
    width: hp(30),
    height: hp(30),
    tintColor: 'white',
    resizeMode: 'contain',
  },
  imageRemoveButtonContainer: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: '#00000066',
    borderRadius: 15,
    width: 14,
    height: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeIconStyle: {
    width: 7,
    height: 7,
    resizeMode: 'contain',
    right: 1,
  },
  purposeRightSideIcon: {
    width: hp(10),
    height: hp(15),
    resizeMode: 'contain',
    tintColor: colors.black,
  },
  purposeCancelContainer: {
    width: hp(15),
    height: hp(15),
    backgroundColor: 'black',
    borderRadius: 50,
  },
  purposeCancelXIcon: {
    color: 'silver',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  noPurposeText: {
    color: 'grey',
  },
  purposeBottomSheet: {
    fontSize: 18,
    fontFamily: fontFamily.poppins600,
    color: 'black',
  },
  bottomSheetLine: {
    width: '100%',
    borderColor: colors.silver,
    borderWidth: 0.7,
    marginTop: 10,
    marginBottom: 10,
  },
  bottomSheetOptionText: {
    color: 'black',
    marginTop: 15,
  },
  basicInfoContainer: {
    flex: 1,
    marginTop: hp(20),
    marginHorizontal: hp(17),
  },
  BODContainer: {
    marginTop: 20,
  },
  dateContainer: {
    flexDirection: 'row',
    // backgroundColor: 'orange',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  dateStyle: {
    color: colors.black,
    fontSize: fontSize(16),
    fontFamily: fontFamily.poppins600,
  },
  datePickerModal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  dateModalBody: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    position: 'relative',
  },
  dateModalCloseButtonContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  dateModalCancelText: {
    fontSize: 24,
    color: 'black',
  },
  dateModalPicker: {
    marginTop: 25,
  },
  dateModalSetDateButton: {
    marginTop: 20,
    backgroundColor: 'black',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 30,
  },
  modalSetDateText: {
    color: '#fff',
    fontSize: 16,
  },
  aboutTextContainer: {
    marginTop: hp(15),
    marginLeft: wp(17),
    marginBottom: hp(10),
  },
  currentlyBottomSheetContainer: {
    padding: 20,
  },
  currentlyBottomSheetOption: {
    marginBottom: hp(15),
  },

  hobbiesAndInterestContainer: {
    flexDirection: 'row',
    marginTop: hp(25),
    marginHorizontal: wp(17),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  saveButtonContainer: {
    marginHorizontal: wp(17),
  },
  saveButtonGradientContainer: {
    width: '100%',
    height: 50,
    borderRadius: 30,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    marginBottom: hp(20),
  },
  saveTextButton: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
});
