import {StyleSheet} from 'react-native';
import {colors} from '../../../utils/colors';
import {fontFamily, fontSize, hp, isIOS, wp} from '../../../utils/helpers';

export const style = StyleSheet.create({
  container: {
    backgroundColor: colors.white,
  },
  toastContainer: {
    flex: 1,
    zIndex: 99,
    position: 'absolute',
    alignSelf: 'center',
    top: -130,
  },
  shimmerContainer: {
    height: hp(449),
    marginHorizontal: 17,
  },
  shimmerBox: {
    width: '100%',
    height: hp(449),
    borderRadius: 10,
    marginBottom: hp(13),
  },
  shimmerBoxBody: {
    marginTop: -180,
    marginHorizontal: 17,
  },
  shimmerSecondBox: {
    width: 100,
    height: 20,
  },
  shimmerThirdBoxContainer: {
    marginTop: 10,
  },
  shimmerThirdBox: {
    width: 100,
    height: 5,
  },
  shimmerBottomContainer: {
    marginTop: 50,
    flexDirection: 'row',
  },
  shimmerBottomContainerBox: {
    width: wp(120),
    height: hp(40),
    justifyContent: 'center',
    marginRight: 40,
  },
  TDBContainer: {
    flex: 1,
  },
  TDBTopContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  TDBBodyContainer: {
    marginHorizontal: 30,
    marginTop: 20,
  },
  TDBImages: {
    width: hp(17),
    height: hp(17),
    resizeMode: 'contain',
    marginRight: hp(22),
  },
  TDBTittleText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  TDBBodySecondContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(20),
  },
  BlockModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalModalBody: {
    width: wp(350),
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  blockModalFirstTittle: {
    fontSize: fontSize(16),
    color: 'black',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    marginTop: 20,
  },
  blockModalSecondTittle: {
    fontSize: fontSize(16),
    color: 'black',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(30),
  },
  blockModalYesButtonContainer: {
    width: hp(122),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  blockModalYesButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalNoButtonContainer: {
    width: wp(122),
    height: hp(50),
    borderRadius: 50,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent',
  },
  blockModalBoButtonSecondContainer: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  blockModalNoButtonText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  ReportContainer: {
    flex: 1,
  },
  ReportBody: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: hp(24),
    alignItems: 'center',
    marginHorizontal: 17,
  },
  reportBackButtonContainer: {
    position: 'absolute',
    left: 0,
  },
  reportBackIcon: {
    width: hp(18),
    height: hp(18),
  },
  ReportText: {
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  reportUnderline: {
    width: '100%',
    height: 0.7,
    backgroundColor: '#E7E7E7',
    marginTop: hp(20),
  },
  reportQuestionText: {
    textAlign: 'center',
    marginTop: hp(15),
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  reportBodyContainer: {
    alignItems: 'center',
    marginTop: hp(9),
  },
  reportBodyText: {
    color: '#8F8F8F',
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  reportTextInputContainer: {
    marginTop: hp(28),
    marginHorizontal: 17,
  },
  reportTextInput: {
    borderWidth: 1,
    borderColor: colors.black,
    padding: 10,
    marginBottom: 20,
    borderRadius: 10,
    height: hp(120),
    textAlignVertical: 'top',
  },
  reportSubmitButtonContainer: {
    width: '100%',
    height: hp(50),
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportSubmitButtonText: {
    color: colors.white,
    marginLeft: hp(20),
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
  },
  reportTextInputReasonContainer: {
    marginTop: hp(25),
    marginHorizontal: 17,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  reportTittleContainer: {
    marginTop: hp(26),
    marginHorizontal: 17,
  },
  reportTittleText: {
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  reportTittleBody: {
    marginTop: hp(28),
  },
  reportModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  reportModalBody: {
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
    width: '85%',
  },
  reportModalTittle: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
    textAlign: 'center',
    marginTop: hp(43),
  },
  reportModalSecondTittleContainer: {
    marginTop: hp(38),
    alignItems: 'center',
  },
  reportModalSecondTittle: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  reportModalButtonContainer: {
    marginTop: hp(38),
    marginBottom: hp(43),
  },
  reportModalButtonBody: {
    width: hp(131),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportModalButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  toastsBody: {
    backgroundColor: '#333333', // Toast background color
    borderRadius: 100,
    marginHorizontal: 20,
    width: wp(300),
    height: hp(55),
    justifyContent: 'center',
  },
  toastsText: {
    color: 'white', // Toast text color
    fontSize: fontSize(16),
    textAlign: 'center',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  renderContainer: {
    marginHorizontal: 17,
  },
  userImageStyle: {
    width: '100%',
    height: hp(449),
    borderRadius: 10,
    marginBottom: hp(13),
  },
  gradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 10,
    width: '100%',
    height: '40%',
    marginBottom: hp(13),
  },
  UserDetailsContainer: {
    position: 'absolute',
    bottom: 35,
    width: '100%',
    marginLeft: wp(21),
  },
  onlineBodyStyle: {
    width: wp(34.8),
    height: hp(12),
    borderRadius: 5,
    backgroundColor: '#24FF00A8',
    justifyContent: 'center',
  },
  bodyTextStyle: {
    color: colors.black,
    fontSize: fontSize(9),
    lineHeight: hp(12),
    textAlign: 'center',
  },
  userNameTextStyle: {
    color: colors.white,
    fontSize: fontSize(24),
    lineHeight: hp(36),
    fontFamily: fontFamily.poppins700,
    marginTop: 5,
  },
  userDetailsDescriptionContainer: {
    flexDirection: 'row',
  },
  userDetailsTextStyle: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(14),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  verticalLineStyle: {
    width: hp(1),
    backgroundColor: colors.gray,
    marginHorizontal: wp(10),
  },
  renderBottomContainer: {
    marginTop: hp(15),
    flexDirection: 'row',
    alignItems: 'center',
  },
  gradientImageBody: {
    width: wp(105),
    height: hp(30),
    resizeMode: 'stretch',
    borderRadius: 50, // Adjust the radius as needed
    overflow: 'hidden',
  },
  gradientImageContainer: {
    position: 'absolute',
    left: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  coupleImage: {
    width: hp(16),
    height: hp(14),
    resizeMode: 'contain',
    tintColor: 'white',
  },
  percentageText: {
    color: 'white',
    marginLeft: 9,
    fontSize: fontSize(10),
    lineHeight: hp(15),
    fontFamily: fontFamily.poppins600,
    top: 1,
  },
  imageAndThreeDotContainer: {
    flexDirection: 'row',
    position: 'absolute',
    right: 35,
  },
  ImagesContainer: {
    width: hp(60),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  cameraIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    marginRight: wp(10),
  },
  threeDotContainer: {
    width: hp(30),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  threeDotImage: {
    width: 4,
    height: 14,
    tintColor: colors.white,
  },
  blockedTittleContainer: {
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: 5,
  },
  blockedText: {
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    marginRight: hp(11),
  },
  blockedIcon: {
    tintColor: '#FF0000',
    height: hp(22),
    width: hp(22),
    resizeMode: 'contain',
  },
  blockedUnderLine: {
    width: '100%',
    borderColor: '#E8E8E8',
    borderWidth: 0.7,
    marginTop: 21,
    marginBottom: 23,
  },
});
