import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, wp} from '../../utils/helpers';

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainer: {
    height: hp(80),
  },
  headerContainerTittleStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  customerHeaderLogo: {
    width: wp(96),
    height: hp(24),
    resizeMode: 'contain',
    marginTop: hp(14),
    marginLeft: wp(17),
  },
  profileLogoStyle: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
    resizeMode: 'cover',
    marginTop: hp(14),
    marginRight: wp(20),
  },
  flatListStatusBarStyle: {
    flexDirection: 'row',
    paddingHorizontal: wp(17),
    marginTop: hp(22),
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  statusBarContainerStyle: {
    height: hp(44),
    flexDirection: 'row',
    borderRadius: 29,
    alignItems: 'center',
    marginRight: wp(10),
    width: hp(125),
    justifyContent: 'center',
  },
  statusBarIconStyle: {
    width: hp(14),
    height: hp(14),
    // borderRadius: 50,
    resizeMode: 'contain',
    // marginLeft: wp(10),
    marginRight: wp(10),
  },
  statusBarTittleTextStyle: {
    color: colors.black,
    fontFamily: fontFamily.poppins500,
    fontSize: fontSize(12),
    lineHeight: hp(21),
    marginRight: wp(13),
  },
  containerBodyStyle: {
    flex: 1,
    marginHorizontal: wp(17),
    marginTop: hp(8),
    // backgroundColor: 'orange',
  },
  userImageStyle: {
    width: '100%',
    height: hp(449),
    borderRadius: 18,
    marginBottom: hp(13),
  },
  UserDetailsContainer: {
    position: 'absolute',
    bottom: 35,
    width: '100%',
    marginLeft: wp(21),
    // backgroundColor: 'grey',
    // backgroundColor: 'rgba(0,0,0,0.05)',
  },
  onlineBodyStyle: {
    width: wp(34.8),
    height: hp(12),
    borderRadius: 5,
    backgroundColor: '#24FF00A8',
    justifyContent: 'center',
  },
  bodyTextStyle: {
    color: colors.black,
    fontSize: fontSize(9),
    lineHeight: hp(12),
    textAlign: 'center',
  },
  userNameTextStyle: {
    color: colors.white,
    fontSize: fontSize(24),
    lineHeight: hp(36),
    fontFamily: fontFamily.poppins700,
    marginTop: 5,
  },
  userDetailsTextStyle: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  verticalLineStyle: {
    width: hp(1),
    backgroundColor: colors.gray,
    marginHorizontal: wp(10),
  },
  userDetailsDescriptionContainer: {
    flexDirection: 'row',
  },
  bottomImageContainer: {
    flexDirection: 'row',
    marginTop: hp(22),
  },
  gradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 18,
    width: '100%',
    height: '40%',
    marginBottom: hp(13),
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  modalBodyStyle: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: wp(340),
    height: hp(550),
  },
  modalTittleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(25),
    marginHorizontal: 20,
  },
  tittleTextModal: {
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins500,
    color: colors.black,
  },
  tittleTextNum: {
    color: colors.blue,
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins500,
  },
  cancelIconContainer: {
    position: 'absolute',
    right: 0,
    height: hp(24),
    width: hp(24),
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelIcon: {
    width: hp(17),
    height: hp(17),
    resizeMode: 'contain',
  },
  matchImageContainer: {
    marginTop: hp(26),
    flexDirection: 'row',
    alignSelf: 'center',
  },
  firstImageStyle: {
    width: hp(64),
    height: hp(64),
    borderRadius: 50,
    marginRight: -15,
    zIndex: 1,
  },
  secondImageStyle: {
    width: hp(64),
    height: hp(64),
    borderRadius: 50,
  },
  matchNameContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: hp(15),
  },
  coupleIcon: {
    width: hp(16),
    height: hp(14),
    resizeMode: 'contain',
    tintColor: '#8225AF',
    marginRight: wp(10),
  },
  matchName: {
    color: colors.black,
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins500,
  },
  underLineStyle: {
    width: '100%',
    borderWidth: 0.5,
    borderColor: '#EAEAEA',
    marginTop: hp(17),
  },
  modalBodyDescription: {
    color: colors.blue,
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins500,
    textAlign: 'center',
    marginTop: hp(17),
  },
  modalBodyContainer: {
    marginHorizontal: 20,
    marginTop: hp(13),
  },
  tittleTextStyle: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  subTittleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  subTittleText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: colors.black,
  },
  checkIcon: {
    width: hp(18),
    height: hp(18),
    resizeMode: 'contain',
    tintColor: colors.blue,
  },
  subTittleUpperContainer: {
    marginTop: hp(14),
  },
  modalBottomNavigationContainer: {
    flex: 1,
    flexDirection: 'row',
    width: '90%',
    position: 'absolute',
    bottom: 30,
    justifyContent: 'space-evenly',
    alignSelf: 'center',
  },
  previousBackIconContainer: {
    width: wp(30),
    alignItems: 'center',
  },
  previousBackIcon: {
    width: hp(12),
    height: hp(24),
    resizeMode: 'contain',
    transform: [{rotate: '180deg'}],
    // tintColor: step === 1 ? '#E4E4E4' : 'black',
  },
  bottomPagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomPaginationStyle: {
    width: 14,
    height: 14,
    borderRadius: 50,
    marginHorizontal: 10,
  },
  nextIconContainer: {
    width: wp(30),
    alignItems: 'center',
  },
  nextIcon: {
    width: hp(12),
    height: hp(24),
    resizeMode: 'contain',
  },

  renderContainer: {
    marginHorizontal: 17,
  },
  imageStyle: {
    width: hp(20),
    height: hp(20),
    resizeMode: 'contain',
  },
  videoStyle: {
    width: hp(25),
    height: hp(20),
    resizeMode: 'contain',
    marginLeft: wp(22),
  },
  starImageContainer: {
    position: 'absolute',
    right: 40,
  },
  startImageStyle: {
    width: hp(22),
    height: hp(20),
    resizeMode: 'contain',
  },
  RenderBottomImageContainer: {
    marginTop: hp(22),
    flexDirection: 'row',
  },
  renderBottomButtonContainer: {
    flexDirection: 'row',
    marginTop: hp(20),
    justifyContent: 'space-between',
  },
  requestDeclineContainer: {
    width: wp(310),
    height: hp(40),
    borderRadius: 20,
    backgroundColor: '#303030',
    justifyContent: 'center',
  },
  requestTextStyle: {
    color: colors.white,
    textAlign: 'center',
    fontFamily: fontFamily.poppins500,
    lineHeight: hp(21),
    fontSize: fontSize(14),
  },
  acceptedButtonContainer: {
    width: wp(310),
    height: hp(40),
    borderRadius: 20,
    backgroundColor: '#303030',
    justifyContent: 'center',
  },
  acceptedTextStyle: {
    color: colors.white,
    textAlign: 'center',
    fontFamily: fontFamily.poppins500,
    lineHeight: hp(21),
    fontSize: fontSize(14),
  },
  declineTextStyle: {
    color: colors.black,
    textAlign: 'center',
    fontFamily: fontFamily.poppins400,
    fontSize: fontSize(14),
    lineHeight: hp(21),
  },
  acceptButtonGradient: {
    width: wp(142),
    height: hp(40),
    borderRadius: 20,
    justifyContent: 'center',
    marginRight: 40,
  },
  acceptTextStyle: {
    color: colors.white,
    textAlign: 'center',
    fontFamily: fontFamily.poppins500,
    fontSize: fontSize(14),
    lineHeight: hp(21),
  },
  receivedShimmerContainer: {
    height: hp(449),
    marginHorizontal: 17,
  },
  receivedShimmerImageBody: {
    width: '100%',
    height: hp(449),
    borderRadius: 10,
    marginBottom: hp(13),
  },
  receivedShimmerImageBodyInside: {
    marginTop: -180,
    marginHorizontal: 17,
  },
  receivedShimmerName: {
    width: 100,
    height: 20,
  },
  receivedShimmerInsideOne: {
    marginTop: 10,
  },
  receivedShimmerData: {
    width: 100,
    height: 5,
  },
  receivedShimmerButtonContainer: {
    marginTop: 50,
    flexDirection: 'row',
  },
  receivedShimmerButton: {
    width: wp(142),
    height: hp(40),
    justifyContent: 'center',
    marginRight: 40,
  },
});

export default style;
