import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, wp} from '../../utils/helpers';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainer: {
    width: '100%',
    height: hp(145),
  },
  headerDescriptionContainer: {
    alignItems: 'center',
    marginTop: hp(40),
  },
  headerTittleTextStyle: {
    color: colors.white,
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins600,
  },

  headerBody: {
    marginHorizontal: wp(17),
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(12),
  },
  appLogoStyle: {
    width: wp(96),
    height: hp(24),
    resizeMode: 'contain',
    marginTop: hp(2),
  },
  dropDownTopImage: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
    marginRight: hp(10.5),
    resizeMode: 'cover',
    right: -7,
    marginTop: hp(2),
  },
  itemContainer: {
    width: '100%',
    height: hp(113),
    borderRadius: 20,
    marginBottom: 17,
    backgroundColor: colors.white,
    alignSelf: 'center',
    borderColor: '#EBEBEB', // Border color
    borderWidth: 1,
  },
  renderContainer: {
    marginHorizontal: wp(18),
  },
  renderLabelContainer: {
    marginTop: hp(25),
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: hp(27),
  },
  renderLabelText: {
    color: '#8225AF',
    fontFamily: fontFamily.poppins600,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    width: '40%',
  },
  renderLabelTexts: {
    color: colors.black,
    fontFamily: fontFamily.poppins600,
    fontSize: fontSize(16),
    lineHeight: hp(24),
  },
  renderPriceContainer: {
    marginLeft: wp(20),
    flexDirection: 'row',
  },
  renderPriceText: {
    fontSize: fontSize(24),
    lineHeight: hp(36),
    fontFamily: fontFamily.poppins700,
    color: 'black',
  },
  renderDiscountContainer: {
    flexDirection: 'row',
    marginTop: hp(3),
    marginLeft: wp(165),
  },
  renderDiscountPrice: {
    textDecorationLine: 'line-through',
    color: colors.black,
    fontFamily: fontFamily.poppins600,
    fontSize: fontSize(16),
    lineHeight: hp(24),
  },
  renderDiscountBody: {
    width: hp(77),
    height: hp(24),
    backgroundColor: '#A7F7D1',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: hp(10),
  },
  renderDiscountBodyText: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
    color: colors.black,
  },
  renderImageContainer: {
    position: 'absolute',
    right: 15,
    marginTop: hp(50),
  },
  renderImageStyle: {
    width: hp(8),
    height: hp(14),
    tintColor: '#EBEBEB',
  },
  choosePlanTextStyle: {
    textAlign: 'center',
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    marginTop: hp(18),
    marginBottom: hp(18),
  },
  bottomTittleText: {
    color: colors.black,
    textAlign: 'center',
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    // marginTop: hp(20),
    marginBottom: hp(22),
  },
  querySubTittle: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  querySubTittleContainer: {
    paddingHorizontal: 17,
    marginBottom: hp(25),
  },
  queryTittle: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
  },
  queryTittleContainer: {
    flexDirection: 'row',
    marginHorizontal: 17,
    marginBottom: hp(22),
    marginTop: hp(22),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  queryBorderCenterLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#EBEBEB',
  },
  bottomQueryBody: {
    width: '100%',
    borderColor: '#EBEBEB',
    borderWidth: 1,
    borderRadius: 14,
  },
  bottomSheetOneMonthText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: '#8225AF',
  },
  oneMonthPriceText: {
    color: colors.black,
    fontSize: fontSize(30),
    lineHeight: hp(54),
    fontFamily: fontFamily.poppins700,
  },
  oldPriceText: {
    textDecorationLine: 'line-through',
    color: colors.black,
    fontSize: fontSize(18),
    lineHeight: hp(27),
    fontFamily: fontFamily.poppins600,
  },
  offerContainer: {
    width: wp(93),
    height: hp(29),
    borderRadius: 14,
    backgroundColor: '#A7F7D1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerTextStyle: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
  },
  headingLine: {
    marginTop: hp(24),
    width: '100%',
    borderWidth: 0.7,
    borderColor: '#EDEDED',
    marginBottom: 24,
  },
  bodyTittleText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: '#8225AF',
  },
  tittleBodyContainer: {
    marginTop: hp(15),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tittleOneTextStyle: {
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  tittleTextColor: {
    fontFamily: fontFamily.poppins600,
  },
  checkIcon: {
    width: hp(14),
    height: hp(14),
    resizeMode: 'contain',
  },
  planSummeryTittle: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: colors.black,
  },
  planSummerySubTittle: {
    fontFamily: fontFamily.poppins400,
  },
  planSummaryPrice: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: colors.black,
  },
  totalText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
  },
  payButtonColorGradient: {
    width: '100%',
    height: hp(50),
    borderRadius: 25,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  payButtonText: {
    textAlign: 'center',
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
});
