import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, isIOS, wp} from '../../utils/helpers';

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainer: {
    width: '100%',
    height: hp(218),
  },
  headerTittleStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerLogoStyle: {
    width: hp(96),
    height: hp(24),
    resizeMode: 'stretch',
    marginTop: hp(14),
    marginLeft: wp(17),
  },
  profileImageStyle: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
    marginTop: hp(14),
    marginRight: hp(18),
    resizeMode: 'cover',
  },
  headerDescriptionContainer: {
    alignItems: 'center',
    marginTop: hp(50),
  },
  headerTittleTextStyle: {
    color: colors.white,
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontWeight: '600',
    marginBottom: hp(12),
  },
  headerTittleDescriptionTextStyle: {
    color: colors.white,
    fontSize: fontSize(10),
    lineHeight: hp(15),
    fontWeight: '400',
  },
  itemContainer: {
    marginTop: 10,
    width: wp(340),
    height: hp(91),
    borderRadius: 15,
    marginBottom: 1,
    backgroundColor: colors.white,
    alignSelf: 'center',
    borderColor: colors.blue, // Border color
    elevation: 1, // Add shadow
    shadowColor: colors.blue, // Shadow color
    shadowOffset: {width: 0, height: 2}, // Shadow offset
    shadowOpacity: 0.5, // Shadow opacity
    shadowRadius: 2, // Shadow radius
  },
  bottomSheetOneMonthText: {
    textAlign: 'center',
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  oneMonthPriceText: {
    color: colors.black,
    fontSize: fontSize(54),
    lineHeight: hp(81),
    fontFamily: fontFamily.poppins700,
    textAlign: 'center',
  },
  bottomSheetHeadingBodyContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
  },
  InrText: {
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  oldPriceText: {
    textDecorationLine: 'line-through',
    marginLeft: 5,
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  offerContainer: {
    width: wp(84),
    height: hp(28),
    borderRadius: 14,
    backgroundColor: '#F0FCF6',
    marginLeft: wp(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerTextStyle: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
    color: '#17C270',
  },
  headingLine: {
    marginTop: hp(25),
    width: '100%',
    borderWidth: 1,
    borderColor: '#E3E3E3',
  },
  bodyTittleText: {
    fontSize: fontSize(16),
    lineHeight: hp(28),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
    textAlign: 'center',
    marginTop: hp(20),
  },
  tittleBodyContainer: {
    marginHorizontal: wp(30),
    marginTop: hp(18),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tittleOneTextStyle: {
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  tittleTextColor: {
    color: colors.blue,
  },
  checkIcon: {
    width: hp(14),
    height: hp(14),
    resizeMode: 'contain',
  },
  bottomSheetBottomButtonContainer: {
    flexDirection: 'row',
    marginHorizontal: wp(30),
    justifyContent: 'space-between',
    marginTop: isIOS ? hp(30) : hp(50),
  },
  notNowButtonColorGradient: {
    width: wp(110),
    height: hp(50),
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent', // Set border color to transparent
  },
  notNowButtonContainer: {
    borderRadius: 10, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  notNowButtonText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
  },
  payButtonColorGradient: {
    width: wp(178),
    height: hp(50),
    borderRadius: 10,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  payButtonText: {
    textAlign: 'center',
    color: colors.white,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins600,
  },
  payButtonIcon: {
    width: hp(14),
    height: hp(14),
    resizeMode: 'contain',
    transform: [{rotate: '90deg'}],
    marginLeft: wp(14),
  },
  headingBodYContainer: {
    width: wp(335),
    height: hp(60),
    borderWidth: 1,
    borderColor: colors.blue,
    alignSelf: 'center',
    borderRadius: 30,
    backgroundColor: colors.white,
    top: -30,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  silverTouchableFunctionality: {
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: hp(6),
    overflow: 'hidden',
  },
  silverTextContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
  },
  silverText: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontWeight: '500',
  },
  goldContainer: {
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  goldBodyContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
  },
  goldText: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontWeight: '500',
  },
  platinumBodyContainer: {
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: hp(6),
    overflow: 'hidden',
  },
  platinumBody: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
  },
  platinumText: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontWeight: '500',
  },
  choiceDescriptionText: {
    textAlign: 'center',
    color: colors.black,
    marginBottom: hp(24),
  },
});

export default style;
