import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, isIOS, wp} from '../../utils/helpers';

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainer: {
    width: '100%',
    height: hp(218),
  },
  headerTittleStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerLogoStyle: {
    width: hp(96),
    height: hp(24),
    resizeMode: 'stretch',
    marginTop: hp(14),
    marginLeft: wp(17),
  },
  profileImageStyle: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
    marginTop: hp(14),
    marginRight: hp(18),
    resizeMode: 'cover',
  },
  headerDescriptionContainer: {
    alignItems: 'center',
    marginTop: hp(50),
  },
  headerTittleTextStyle: {
    color: colors.white,
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins600,
    marginBottom: hp(12),
  },
  headerTittleDescriptionTextStyle: {
    color: colors.white,
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
  },
  itemContainer: {
    // marginTop: 10,
    // width: wp(355),
    width: '100%',
    height: hp(113),
    borderRadius: 20,
    marginBottom: 17,
    backgroundColor: colors.white,
    alignSelf: 'center',
    borderColor: '#EBEBEB', // Border color
    // elevation: 1, // Add shadow
    // shadowColor: colors.blue, // Shadow color
    // shadowOffset: {width: 0, height: 2}, // Shadow offset
    // shadowOpacity: 0.5, // Shadow opacity
    // shadowRadius: 2, // Shadow radius
    borderWidth: 1,
  },
  bottomSheetOneMonthText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: '#8225AF',
  },
  oneMonthPriceText: {
    color: colors.black,
    fontSize: fontSize(30),
    lineHeight: hp(54),
    fontFamily: fontFamily.poppins700,
  },

  InrText: {
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  oldPriceText: {
    textDecorationLine: 'line-through',
    color: colors.black,
    fontSize: fontSize(18),
    lineHeight: hp(27),
    fontFamily: fontFamily.poppins600,
  },
  offerContainer: {
    width: wp(93),
    height: hp(29),
    borderRadius: 14,
    backgroundColor: '#A7F7D1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerTextStyle: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
  },
  headingLine: {
    marginTop: hp(24),
    width: '100%',
    borderWidth: 0.7,
    borderColor: '#EDEDED',
    marginBottom: 24,
  },
  bodyTittleText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: '#8225AF',
  },
  tittleBodyContainer: {
    marginTop: hp(15),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tittleOneTextStyle: {
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  tittleTextColor: {
    fontFamily: fontFamily.poppins600,
  },
  checkIcon: {
    width: hp(14),
    height: hp(14),
    resizeMode: 'contain',
  },
  bottomSheetBottomButtonContainer: {
    // flexDirection: 'row',
    // marginHorizontal: wp(30),
    // justifyContent: 'space-between',
    // marginTop: isIOS ? hp(30) : hp(50),
    marginHorizontal: 24,
    marginTop: 32,
  },
  notNowButtonColorGradient: {
    width: wp(110),
    height: hp(50),
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent', // Set border color to transparent
  },
  notNowButtonContainer: {
    borderRadius: 10, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  notNowButtonText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
  },
  payButtonColorGradient: {
    width: '100%',
    height: hp(50),
    borderRadius: 25,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  payButtonText: {
    textAlign: 'center',
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  payButtonIcon: {
    width: hp(14),
    height: hp(14),
    resizeMode: 'contain',
    transform: [{rotate: '90deg'}],
    marginLeft: wp(14),
  },
  headingBodYContainer: {
    // width: wp(335),
    width: '100%',
    height: hp(60),
    borderWidth: 1,
    borderColor: colors.blue,
    alignSelf: 'center',
    borderRadius: 30,
    backgroundColor: colors.white,
    top: -30,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginHorizontal: 18,
  },
  silverTouchableFunctionality: {
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: hp(6),
    overflow: 'hidden',
  },
  silverTextContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
  },
  silverText: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontWeight: '500',
  },
  goldContainer: {
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  goldBodyContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
  },
  goldText: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontWeight: '500',
  },
  platinumBodyContainer: {
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: hp(6),
    overflow: 'hidden',
  },
  platinumBody: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: 25,
    width: wp(107),
    height: hp(50),
  },
  platinumText: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontWeight: '500',
  },
  choiceDescriptionText: {
    textAlign: 'center',
    color: colors.black,
    marginBottom: hp(24),
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    // marginTop: -20,
  },

  bottomTittleText: {
    color: colors.black,
    textAlign: 'center',
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    marginTop: hp(20),
    marginBottom: hp(22),
  },
  bottomQueryBody: {
    width: '100%',
    borderColor: '#EBEBEB',
    borderWidth: 1,
    borderRadius: 14,
  },
  queryTittleContainer: {
    flexDirection: 'row',
    marginHorizontal: 17,
    marginBottom: hp(22),
    marginTop: hp(22),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  queryTittle: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
  },
  querySubTittle: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  querySubTittleContainer: {
    paddingHorizontal: 17,
    marginBottom: hp(25),
  },
  queryBorderCenterLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#EBEBEB',
  },
  planSummeryTittle: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: colors.black,
  },
  planSummerySubTittle: {
    fontFamily: fontFamily.poppins400,
  },
  planSummaryPrice: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: colors.black,
  },
  totalText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
  },
  gstTextStyle: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
});

export default style;
