import {StyleSheet} from 'react-native';
import {colors} from '../../../utils/colors';
import {fontFamily, fontSize, hp, isIOS, wp} from '../../../utils/helpers';

const style = StyleSheet.create({
  container: {backgroundColor: colors.white},

  emptyListContainer: {
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemContainer: {
    flexDirection: 'row',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  image: {
    width: hp(50),
    height: hp(50),
    borderRadius: 25,
    marginRight: hp(10),
  },
  textContainer: {
    justifyContent: 'center',
  },
  name: {
    fontSize: fontSize(16),
    fontWeight: 'bold',
  },
  gender: {
    fontSize: fontSize(14),
    color: '#555',
  },
  listContainer: {
    paddingBottom: 200,
  },

  userImageStyle: {
    width: '100%',
    height: hp(449),
    borderRadius: 18,
    marginBottom: hp(13),
  },

  gradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 18,
    width: '100%',
    height: '40%',
    marginBottom: hp(13),
  },
  UserDetailsContainer: {
    position: 'absolute',
    bottom: 35,
    width: '100%',
    marginLeft: wp(21),
  },
  onlineBodyStyle: {
    width: wp(34.8),
    height: hp(12),
    borderRadius: 5,
    backgroundColor: '#24FF00A8',
    justifyContent: 'center',
  },
  bodyTextStyle: {
    color: colors.black,
    fontSize: fontSize(9),
    lineHeight: hp(12),
    textAlign: 'center',
  },

  userNameTextStyle: {
    color: colors.white,
    fontSize: fontSize(24),
    lineHeight: hp(36),
    fontFamily: fontFamily.poppins700,
    marginTop: hp(5),
  },
  userDetailsDescriptionContainer: {
    flexDirection: 'row',
  },
  userDetailsTextStyle: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },

  verticalLineStyle: {
    width: hp(1),
    backgroundColor: colors.gray,
    marginHorizontal: wp(10),
  },

  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  modalBodyStyle: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: wp(340),
    height: hp(550),
  },
  modalTittleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(25),
    marginHorizontal: 20,
  },
  tittleTextModal: {
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins500,
    color: colors.black,
  },
  tittleTextNum: {
    color: colors.blue,
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins500,
  },
  cancelIconContainer: {
    position: 'absolute',
    right: -5,
    height: hp(25),
    width: hp(25),
    justifyContent: 'center',
    alignItems: 'center',
    top: -15,
    // backgroundColor: '#B0B0B0',
    // borderRadius: 25,
  },
  cancelIcon: {
    width: hp(13),
    height: hp(13),
    // resizeMode: 'contain',
    tintColor: 'black',
  },
  matchImageContainer: {
    marginTop: hp(26),
    flexDirection: 'row',
    alignSelf: 'center',
  },
  firstImageStyle: {
    width: hp(64),
    height: hp(64),
    borderRadius: 50,
    marginRight: -15,
    zIndex: 1,
  },
  secondImageStyle: {
    width: hp(64),
    height: hp(64),
    borderRadius: 50,
  },
  matchNameContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: hp(15),
  },
  coupleIcon: {
    width: hp(16),
    height: hp(14),
    resizeMode: 'contain',
    tintColor: '#8225AF',
    marginRight: wp(10),
  },
  matchName: {
    color: colors.black,
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins500,
  },
  underLineStyle: {
    width: '100%',
    borderWidth: 0.8,
    borderColor: '#EAEAEA',
    marginTop: hp(17),
  },
  modalBodyDescription: {
    color: colors.blue,
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins500,
    textAlign: 'center',
    marginTop: hp(17),
  },
  modalBodyContainer: {
    marginHorizontal: 20,
    marginTop: hp(13),
  },
  tittleTextStyle: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  subTittleUpperContainer: {
    marginTop: hp(10),
  },
  subTittleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  subTittleText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins700,
    color: colors.black,
  },
  checkIcon: {
    width: hp(18),
    height: hp(18),
    resizeMode: 'contain',
    // tintColor: colors.blue,
  },
  modalBottomNavigationContainer: {
    flex: 1,
    flexDirection: 'row',
    // width: '90%',
    width: '70%',
    position: 'absolute',
    bottom: 30,
    justifyContent: 'space-evenly',
    alignSelf: 'center',
  },
  previousBackIconContainer: {
    width: wp(30),
    alignItems: 'center',
  },
  previousBackIcon: {
    width: hp(12),
    height: hp(24),
    resizeMode: 'contain',
    transform: [{rotate: '180deg'}],
  },
  bottomPagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomPaginationStyle: {
    width: 14,
    height: 14,
    borderRadius: 50,
    marginHorizontal: 10,
  },
  nextIconContainer: {
    width: wp(30),
    alignItems: 'center',
  },
  nextIcon: {
    width: hp(12),
    height: hp(24),
    resizeMode: 'contain',
  },
  logoIcon: {
    position: 'absolute',
    tintColor: '#fff',
    resizeMode: 'contain',
    width: hp(33),
    height: hp(44),
    alignSelf: 'center',
    marginTop: hp(200),
  },
  profileAvatarText: {
    fontSize: fontSize(60),
    marginTop: -80,
  },
  cardNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  subPlanContainer: {
    height: 22,
    backgroundColor: 'orange',
    marginLeft: 11,
    borderRadius: 50,
    flexDirection: 'row',
    paddingHorizontal: 7,
  },
  crowIcon: {
    width: 11,
    height: 11,
    tintColor: 'white',
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  planNameText: {
    color: 'white',
    fontSize: fontSize(12),
    fontWeight: 'bold',
    alignSelf: 'center',
    marginLeft: 3,
  },
  cardBottomContainer: {
    marginTop: hp(15),
    flexDirection: 'row',
    alignItems: 'center',
  },
  gradientButtonBG: {
    width: wp(105),
    height: hp(30),
    resizeMode: 'stretch',
    borderRadius: 50,
    overflow: 'hidden',
  },
  coupleImgContainer: {
    position: 'absolute',
    left: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  coupleImg: {
    width: hp(16),
    height: hp(14),
    resizeMode: 'contain',
    tintColor: 'white',
  },
  couplePercentageContainer: {
    color: 'white',
    marginLeft: 9,
    fontSize: fontSize(10),
    lineHeight: hp(15),
    fontFamily: fontFamily.poppins600,
    top: 1,
  },
  cardBottomRightCon: {
    flexDirection: 'row',
    position: 'absolute',
    right: 35,
  },
  imageCountCon: {
    width: hp(60),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  cameraImg: {
    width: hp(16),
    height: hp(16),
    resizeMode: 'contain',
    marginRight: wp(10),
  },
  shortListCon: {
    width: hp(30),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 50,
  },
  shortListImg: {
    width: hp(30),
    height: hp(30),
    resizeMode: 'contain',
  },
  threeDotCon: {
    width: hp(30),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  threeDotImg: {
    width: hp(4),
    height: hp(14),
    tintColor: colors.white,
  },
  loadingContainer: {},
  loadingBodyCon: {
    height: hp(449),
    marginHorizontal: 17,
  },
  loadingBodyMain: {
    width: '100%',
    height: hp(449),
    borderRadius: 10,
    marginBottom: hp(13),
  },
  loadingCenterCon: {
    marginTop: -180,
    marginHorizontal: 17,
  },
  loadingCenterOne: {
    width: hp(100),
    height: hp(20),
  },
  loadingCenterTwo: {
    width: hp(100),
    height: hp(5),
  },
  loadingBottomCon: {
    marginTop: hp(50),
    flexDirection: 'row',
  },
  loadingBottomButton: {
    width: wp(142),
    height: hp(40),
    justifyContent: 'center',
    marginRight: 40,
  },
  staticToastBody: {
    backgroundColor: '#333333',
    borderRadius: 100,
    marginHorizontal: 20,
    width: wp(300),
    height: hp(55),
    justifyContent: 'center',
  },
  staticToastText: {
    color: 'white', // Toast text color
    fontSize: fontSize(16),
    textAlign: 'center',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  toastDisplayContainer: {
    flex: 1,
    zIndex: 99,
    position: 'absolute',
    alignSelf: 'center',
    top: -130,
  },
  bottomSheetContainer: {
    marginHorizontal: 30,
    marginTop: hp(20),
  },
  firstLitterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bottomSheetIcon: {
    width: hp(17),
    height: hp(17),
    resizeMode: 'contain',
    marginRight: hp(22),
  },
  bottomSheetText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  bottomSheetSubTittle: {
    fontSize: fontSize(12),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
    color: '#7B7B7B',
  },
  bottomSheetLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#EBEBEB',
    marginTop: hp(22),
  },
  blockModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  blockModalBody: {
    width: wp(350),
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  blockModalTittle: {
    fontSize: fontSize(16),
    color: 'black',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    marginTop: 20,
  },
  blockModalSubTittle: {
    fontSize: fontSize(16),
    color: 'black',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalButtonCon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(30),
  },
  blockModalYesBTNCon: {
    width: hp(122),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: hp(20),
  },
  blockModalYesText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalBoBTNCon: {
    width: wp(122),
    height: hp(50),
    borderRadius: 50,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent',
  },
  blockModalBoBTNBody: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  blockModalNoText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  reportCon: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: hp(24),
    alignItems: 'center',
    marginHorizontal: 17,
  },
  reportBackArrowContainer: {
    position: 'absolute',
    left: 0,
  },
  reportBackIcon: {
    width: hp(18),
    height: hp(18),
  },
  reportText: {
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  reportLine: {
    width: '100%',
    height: 0.7,
    backgroundColor: '#E7E7E7',
    marginTop: hp(20),
  },
  reportQuesText: {
    textAlign: 'center',
    marginTop: hp(15),
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  reportReasonCon: {
    alignItems: 'center',
    marginTop: hp(9),
  },
  reportReasonTittle: {
    color: '#8F8F8F',
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  reportAboutCon: {
    marginTop: hp(28),
    marginHorizontal: 17,
  },
  reportAboutTextInput: {
    borderWidth: 1,
    borderColor: colors.black,
    padding: 10,
    marginBottom: 20,
    borderRadius: 10,
    height: hp(120),
    textAlignVertical: 'top',
  },
  submitReportCon: {
    width: '100%',
    height: hp(50),
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitReportText: {
    color: colors.white,
    marginLeft: hp(20),
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
  },
  reportReasonText: {
    marginTop: hp(25),
    marginHorizontal: 17,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  reportReasonContainer: {
    marginTop: hp(26),
    marginHorizontal: 17,
  },
  reportReasonTexts: {
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  successModalCon: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  successModalBody: {
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
    width: '85%',
  },
  successModalTittle: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
    textAlign: 'center',
    marginTop: hp(43),
  },
  successModalSubTittleCon: {
    marginTop: hp(38),
    alignItems: 'center',
  },
  successModalSubTittle: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  successOkCon: {
    marginTop: hp(38),
    marginBottom: hp(43),
  },
  successOkBody: {
    width: hp(131),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successOkBtnText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
});

export default style;
