import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, wp} from '../../utils/helpers';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainer: {
    marginHorizontal: 17,
  },
  headerBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(12),
    alignItems: 'center',
  },
  appLogo: {
    width: wp(96),
    height: hp(24),
    resizeMode: 'contain',
    marginTop: hp(2),
  },
  topBottomSheetLogo: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
    marginRight: hp(10.5),
    resizeMode: 'cover',
    right: -7,
    marginTop: hp(2),
  },
  headerBottomContainer: {
    marginTop: hp(33),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(10),
  },
  headerBottomTittle: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    color: colors.black,
    textAlign: 'center',
  },
  searchFilterContainer: {
    width: hp(28),
    height: hp(28),
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 2,
  },
  searchIcon: {
    width: hp(20),
    height: hp(20),
    resizeMode: 'contain',
  },
  bodyContainer: {
    marginTop: hp(10),
  },
  toastMessageBody: {
    backgroundColor: '#333333', // Toast background color
    borderRadius: 100,
    marginHorizontal: 20,
    width: wp(300),
    height: hp(55),
    justifyContent: 'center',
    marginTop: -20,
  },
  toastMessageText: {
    color: 'white', // Toast text color
    fontSize: fontSize(16),
    textAlign: 'center',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  flatListContainer: {
    marginHorizontal: 17,
  },
  flatListImageBody: {
    width: '100%',
    height: hp(449),
    borderRadius: 18,
    marginBottom: hp(13),
  },
  imageBottomShadow: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 18,
    width: '100%',
    height: '40%',
    marginBottom: hp(13),
  },
  imageBodyDetailContainer: {
    position: 'absolute',
    bottom: 35,
    width: '100%',
    marginLeft: wp(21),
  },
  onlineTextBody: {
    width: wp(34.8),
    height: hp(12),
    borderRadius: 5,
    backgroundColor: '#24FF00A8',
    justifyContent: 'center',
  },
  onlineText: {
    color: colors.black,
    fontSize: fontSize(9),
    lineHeight: hp(12),
    textAlign: 'center',
  },
  nameText: {
    color: colors.white,
    fontSize: fontSize(24),
    lineHeight: hp(36),
    fontFamily: fontFamily.poppins700,
    marginTop: 5,
  },
  userAge: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  userHeightStyle: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  verticalLineStyle: {
    width: hp(1),
    backgroundColor: colors.gray,
    marginHorizontal: wp(10),
  },
  jobTittleText: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  userAddressDetailsContainer: {
    flexDirection: 'row',
  },
  currentCityStyle: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  currentCountryStyle: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  imageBottomImageContainer: {
    marginTop: hp(15),
    flexDirection: 'row',
    alignItems: 'center',
  },
  gradientImageContainer: {
    width: wp(105),
    height: hp(30),
    resizeMode: 'stretch',
    borderRadius: 50, // Adjust the radius as needed
    overflow: 'hidden', // Ensure rounded corners clip the image
  },
  gradientImageButton: {
    position: 'absolute',
    left: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  coupleImage: {
    width: hp(16),
    height: hp(14),
    resizeMode: 'contain',
    tintColor: 'white',
  },
  matchesText: {
    color: 'white',
    marginLeft: 9,
    fontSize: fontSize(10),
    lineHeight: hp(15),
    fontFamily: fontFamily.poppins600,
    top: 1,
  },
  bottomImageContainer: {
    flexDirection: 'row',
    position: 'absolute',
    right: 35,
  },
  cameraImageContainer: {
    width: hp(60),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  cameraImage: {
    width: hp(16),
    height: hp(16),
    resizeMode: 'contain',
    marginRight: wp(10),
  },
  starIconContainer: {
    width: hp(30),
    height: hp(30),
  },
  startIcon: {
    width: hp(30),
    height: hp(30),
    resizeMode: 'contain',
  },
  threeDotContainer: {
    width: hp(30),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  threeDotImage: {
    width: 4,
    height: 14,
    tintColor: colors.white,
  },
  bottomSheetShareContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bottomSheetIcon: {
    width: hp(17),
    height: hp(17),
    resizeMode: 'contain',
    marginRight: hp(22),
  },
  bottomSheetText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  bottomBodyContainers: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(20),
  },
});
