import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, isIOS, wp} from '../../utils/helpers';

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(14),
    // backgroundColor: 'lightblue',
  },
  customHeaderLogo: {
    width: wp(96),
    height: hp(24),
    marginLeft: wp(17),
    resizeMode: 'contain',
  },
  profileLogoStyle: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
    marginRight: wp(17),
    resizeMode: 'stretch',
  },
  userStoryContainer: {
    marginTop: hp(15),
    marginHorizontal: wp(17),
    height: hp(60),
  },
  userProfileImageStyle: {
    width: '100%',
    height: hp(449),
  },
  descriptionTextContainer: {
    marginHorizontal: wp(17),
    marginTop: hp(18),
  },
  descriptionTittleText: {
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins600,
  },
  descriptionBodyText: {
    color: colors.black,
    fontFamily: fontFamily.poppins400,
    fontSize: fontSize(12),
    lineHeight: hp(18),
    marginTop: hp(19),
  },
  UserDetailsContainer: {
    position: 'absolute',
    bottom: 0,
    width: '90%',
    marginRight: wp(17),
    marginHorizontal: wp(17),
  },
  onlineBodyStyle: {
    width: wp(6),
    height: hp(6),
    borderRadius: 5,
    backgroundColor: '#24FF00',
    // justifyContent: 'center',
    marginLeft: wp(5),
    top: 15,
  },
  bodyTextStyle: {
    color: colors.black,
    fontSize: fontSize(8),
    lineHeight: hp(12),
    textAlign: 'center',
  },
  userNameTextStyle: {
    color: colors.white,
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins700,
  },
  bottomImageContainer: {
    flexDirection: 'row',
    marginTop: hp(10),
    // backgroundColor: 'red',
    alignItems: 'center',
  },
  userDetailsDescriptionContainer: {
    flexDirection: 'row',
  },
  userDetailsTextStyle: {
    color: colors.white,
    fontSize: fontSize(10),
    lineHeight: hp(14),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  verticalLineStyle: {
    width: hp(1),
    height: '100%',
    backgroundColor: colors.gray,
    marginHorizontal: wp(5),
  },
  imageBottomContainer: {
    flexDirection: 'row',
    marginTop: hp(22),
  },
  bottomImageStyle: {
    width: hp(20),
    height: hp(20),
    resizeMode: 'contain',
    marginRight: wp(22),
  },
  videoIconStyle: {
    width: hp(24.1),
    height: hp(20),
    resizeMode: 'contain',
  },
  likeIconContainer: {
    position: 'absolute',
    right: 0,
  },
  likeIconStyle: {
    width: hp(21.67),
    height: hp(20),
    resizeMode: 'contain',
  },
  imageIcon: {
    width: hp(20),
    height: hp(20),
    resizeMode: 'contain',
    marginRight: wp(22),
  },
  videoIcon: {
    width: hp(24.1),
    height: hp(20),
    resizeMode: 'contain',
  },
  startIconContainer: {
    marginLeft: wp(22),
  },
  starIcon: {
    width: hp(21.67),
    height: hp(20),
    resizeMode: 'contain',
  },
  likeSharContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 15,
    // marginTop: -10,
    marginTop: 5,
  },
  dislikeIcon: {
    width: hp(40),
    height: hp(40),
    resizeMode: 'contain',
    marginRight: 20,
  },
  likeIcon: {
    width: hp(180),
    height: hp(40),
    resizeMode: 'contain',
    marginRight: 20,
  },
  startIcon: {
    width: hp(40),
    height: hp(40),
    resizeMode: 'contain',
    marginRight: 20,
  },
  shareIcon: {
    width: hp(63),
    height: hp(40),
    resizeMode: 'contain',
  },
  matchesText: {
    // textAlign: 'center',
    fontSize: fontSize(10),
    lineHeight: hp(15),
    fontFamily: fontFamily.poppins600,
    color: colors.white,
  },
  matchesContainer: {
    width: hp(87),
    height: hp(24),
    borderRadius: 15,
    justifyContent: 'center',
    position: 'absolute',
    right: 10,
  },
  bottomSheetContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bottomSheetShareIcon: {
    width: hp(17),
    height: hp(17),
    resizeMode: 'contain',
  },
  bottomSheetTextStyle: {
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    marginLeft: wp(20),
  },
  bottomSheetImageTextSpace: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(20),
  },
  unfriendIcon: {
    width: hp(20),
    height: hp(14),
    resizeMode: 'contain',
  },
  sendMessageIcon: {
    width: hp(17),
    height: hp(17),
    resizeMode: 'contain',
  },
  bottomSheetBodyContainer: {
    flex: 1,
    marginTop: hp(15),
  },
  aboutTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  threeDotIcon: {
    width: hp(20),
    height: hp(20),
    resizeMode: 'contain',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  unfriendModalBody: {
    width: wp(320),
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  unfriendModalTittleText: {
    fontSize: fontSize(16),
    color: 'black',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    marginTop: hp(30),
    textAlign: 'center',
  },
  unfriendModalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(42),
  },
  unfriendYesButtonContainer: {
    width: hp(122),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unfriendButtonTextButton: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  unfriendNoButtonContainer: {
    width: wp(122),
    height: hp(50),
    borderRadius: 50,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent', // Set border color to transparent
  },
  unfriendNoButtonBody: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  unfriendNoButtonText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalBodyContainer: {
    width: wp(350),
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  blockModalTittleText: {
    fontSize: fontSize(16),
    color: 'black',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    marginTop: 20,
  },
  blockModalSubTittleText: {
    fontSize: fontSize(16),
    color: 'black',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(30),
  },
  blockModalYesButtonContainer: {
    width: hp(122),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  blockModalYesButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalMoButtonContainer: {
    width: wp(122),
    height: hp(50),
    borderRadius: 50,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent', // Set border color to transparent
  },
  blockModalNoButtonBody: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  blockModalNoButtonText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  spamModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  spamModalBody: {
    width: '90%',
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  spamModalBodySpace: {
    marginTop: hp(20),
    marginBottom: hp(30),
  },
  spamModalTittleContainer: {
    position: 'relative',
    width: '100%',
  },
  spamModalReportText: {
    textAlign: 'center',
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  spamModalCancelContainer: {
    position: 'absolute',
    right: 0,
    width: hp(24),
    height: hp(24),
    top: 3,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  spamModalCancelIcon: {
    width: hp(14),
    height: hp(14),
    resizeMode: 'contain',
  },
  spamModalBackContainer: {
    position: 'absolute',
    left: 0,
    width: hp(24),
    height: hp(24),
    top: 3,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  spamModalBackIcon: {
    width: hp(14),
    height: hp(14),
    resizeMode: 'contain',
  },
  spamModalUnderLine: {
    width: '100%',
    borderWidth: 0.7,
    borderColor: '#EDEDED',
    marginTop: hp(27),
  },
  spamModalTittle: {
    color: colors.black,
    marginTop: hp(22),
    textAlign: 'center',
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  spamModalBoxBody: {
    marginTop: hp(23),
    width: '100%',
    height: hp(50),
    borderWidth: 1,
    borderRadius: 30,
    justifyContent: 'center',
    borderColor: '#B5B5B5',
  },
  spamModalBocBodyStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  spamModalBoxTextStyle: {
    marginLeft: hp(22),
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  spamModalDropDownIcon: {
    width: hp(11),
    height: hp(6),
    marginRight: hp(22),
  },
  spamModalContinueContainer: {
    marginTop: hp(24),
  },
  spamModalContinueButtonBody: {
    width: '100%',
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spamModalContinueButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  spamModalSpaceTwoTittle: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
    marginTop: hp(23),
  },
  spamModalSpaceSubTittle: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
    marginTop: hp(20),
  },
  spamModalSpaceBodyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: wp(5),
    marginTop: hp(20),
  },
  spamModalSpaceBodyDotStyle: {
    width: 5,
    height: 5,
    backgroundColor: 'black',
    borderRadius: 50,
  },
  spamModalSpaceSubBodyTittle: {
    marginLeft: 15,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  spamModalSpaceSubBodyTittles: {
    marginLeft: 25,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  spamModalSpaceBodyContainerStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: wp(5),
    marginTop: hp(5),
  },
  spamModalSpaceButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(30),
  },
  spamModalSpaceSubmitContainer: {
    width: hp(185),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spamModalSubmitButton: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  spamModalCloseContainer: {
    width: wp(112),
    height: hp(50),
    borderRadius: 50,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent', // Set border color to transparent
  },
  spamModalCloseBodyStyle: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  spamModalCloseButtonText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  spamModalFinalTittleText: {
    textAlign: 'center',
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  spamModalFinalBodyStyle: {
    marginTop: hp(23),
    alignItems: 'center',
  },
  spamModalSubTittleText: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: '#A3A3A3',
  },
  spamModalFinalMiddleText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
    marginTop: hp(15),
  },
  spamModalSpamIcon: {
    width: hp(26),
    height: hp(26),
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: hp(20),
  },
  spamModalSpamText: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
    textAlign: 'center',
    marginTop: hp(12),
  },
  spamModalSpamSubText: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: '#A3A3A3',
    textAlign: 'center',
  },
  spamModalFinalSubmitContainer: {
    width: hp(185),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: hp(24),
  },
  spamModalFinalSubmitButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
});

export default style;
