import {StyleSheet} from 'react-native';
import {colors} from '../../../utils/colors';
import {fontFamily, fontSize, hp} from '../../../utils/helpers';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headingContainer: {
    marginHorizontal: 17,
    top: -20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headingText: {
    color: 'black',
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  editIconContainer: {
    width: hp(30),
    height: hp(30),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: hp(5),
  },
  editIcon: {
    tintColor: 'black',
    width: hp(16),
    height: hp(16),
  },
  horizontalLineOne: {
    width: '100%',
    height: 4,
    backgroundColor: '#F8F8F8',
  },
  bodyContainer: {
    marginTop: hp(19),
  },
  bodyContainerStyle: {
    marginHorizontal: 17,
  },
  tittleText: {
    fontSize: fontSize(14),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  subTittleText: {
    color: colors.black,
    fontSize: fontSize(18),
    lineHeight: hp(28),
    fontFamily: fontFamily.poppins600,
    marginTop: hp(2),
  },
  subTittleContainer: {
    marginTop: hp(20),
  },
  subTittleContainerStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rightSideIcon: {
    width: hp(8),
    height: hp(15),
    marginRight: 8,
    tintColor: '#5F6368',
  },
  horizontalLineTwo: {
    width: '100%',
    height: 4,
    backgroundColor: '#F8F8F8',
    marginTop: hp(15),
    marginBottom: hp(30),
  },
  aboutBottomSheetTittleText: {
    marginHorizontal: 31,
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    marginTop: hp(5),
  },
  aboutBottomSheetBody: {
    backgroundColor: '#F7F7F7',
    marginTop: hp(15),
  },
  aboutBottomSheetTextInput: {
    marginHorizontal: 31,
    marginTop: hp(15),
    height: hp(200),
    textAlignVertical: 'top',
    marginBottom: 15,
    color: 'black',
    fontSize: fontSize(16),
    lineHeight: hp(24),
  },
  aboutBottomSheetWord: {
    textAlign: 'right',
    marginRight: hp(15),
    marginTop: hp(18),
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  bottomSheetAddButtonContainer: {
    width: hp(122),
    height: hp(44),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: hp(32),
  },
  bottomSheetAddButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  bottomSheetTittleText: {
    marginHorizontal: 20,
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    marginTop: 5,
  },
  bottomSheetUnderLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#E7E7E7',
    marginTop: hp(15),
  },
  bottomSheetOptionText: {
    marginHorizontal: 20,
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  BODModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  BODBodyContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    position: 'relative',
  },
  BODCancelButtonContainer: {
    position: 'absolute',
    top: 10,
    right: -1,
    marginBottom: 10,
    width: 50,
    alignItems: 'center',
  },
  BODCancelText: {
    color: 'black',
    fontSize: 24,
    fontFamily: fontFamily.poppins500,
  },
  BODSetDateButton: {
    marginTop: 20,
    backgroundColor: colors.black,
    // paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 30,
    width: '100%',
    height: hp(44),
    justifyContent: 'center',
    // textAlign: 'center',
    alignItems: 'center',
  },
  BODSetDateText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: fontFamily.poppins500,
  },
  BOTModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  BOTModalBodyContainer: {
    width: 300,
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  BOTModalTittle: {
    fontSize: 18,
    marginBottom: 10,
  },
  BOTButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 10,
  },
  BOTConfirmButtonContainer: {
    width: '100%',
    height: hp(44),
    backgroundColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    // marginHorizontal: 5,
    marginTop: hp(10),
  },
  BOTConfirmText: {
    color: colors.white,
    fontSize: fontSize(14),
    fontFamily: fontFamily.poppins500,
  },
  BOTCancelButtonContainer: {
    width: 100,
    height: 50,
    backgroundColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    marginHorizontal: 5,
  },
  BOTCancelText: {
    color: colors.white,
    fontSize: fontSize(14),
    fontFamily: fontFamily.poppins500,
  },
  bottomSheetHeightTextInput: {
    width: '100%',
    height: 50,
    borderWidth: 0.7,
    marginTop: 20,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    fontSize: 20,
    paddingRight: 40,
    color: colors.black,
  },
  BottomSheetTextInputText: {
    position: 'absolute',
    right: 10,
    top: 25,
    fontSize: 24,
    color: 'grey',
  },
  saveButtonContainer: {
    width: '100%',
    height: hp(44),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: hp(32),
    marginBottom: hp(25),
  },
});
