import {StyleSheet} from 'react-native';
import {colors} from '../../../utils/colors';
import {fontFamily, fontSize, hp} from '../../../utils/helpers';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headingContainer: {
    marginHorizontal: 17,
    top: -20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headingText: {
    color: 'black',
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  editIcon: {
    tintColor: 'black',
    width: hp(16),
    height: hp(16),
  },
  editIconContainer: {
    width: hp(30),
    height: hp(30),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: hp(5),
  },
  horizontalLineOne: {
    width: '100%',
    height: 4,
    backgroundColor: '#F8F8F8',
  },
  bodyContainer: {
    marginTop: hp(19),
  },
  bodyContainerStyle: {
    marginHorizontal: 17,
  },
  tittleText: {
    fontSize: fontSize(14),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  subTittleText: {
    color: colors.black,
    fontSize: fontSize(18),
    lineHeight: hp(28),
    fontFamily: fontFamily.poppins600,
    marginTop: hp(2),
  },
  subTittleContainer: {
    marginTop: hp(20),
  },
  rightSideIcon: {
    width: hp(8),
    height: hp(15),
    marginRight: 8,
    tintColor: '#5F6368',
  },
  subTittleContainerStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  aboutBottomSheetBody: {
    backgroundColor: '#F7F7F7',
    marginTop: hp(15),
  },
  aboutBottomSheetTittleText: {
    marginHorizontal: 31,
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    marginTop: 5,
  },
  aboutBottomSheetTextInput: {
    marginHorizontal: 31,
    marginTop: hp(15),
    height: hp(200),
    textAlignVertical: 'top',
    marginBottom: 15,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  aboutBottomSheetWord: {
    textAlign: 'center',

    marginTop: hp(18),
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  bottomSheetAddButtonContainer: {
    width: hp(162),
    height: hp(44),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: hp(32),
  },
  bottomSheetAddButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  saveButtonContainer: {
    width: '100%',
    height: hp(44),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: hp(32),
    marginBottom: hp(25),
  },
  bottomSheetTittleText: {
    marginHorizontal: 20,
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    marginTop: 5,
  },
  bottomSheetUnderLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#E7E7E7',
    marginTop: hp(15),
  },
  bottomSheetOptionText: {
    marginHorizontal: 20,
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  bottomSheetHeightTextInput: {
    width: '100%',
    height: 50,
    borderWidth: 0.7,
    marginTop: 20,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    fontSize: 20,
    paddingRight: 40,
    color: 'black',
  },
  BottomSheetTextInputText: {
    position: 'absolute',
    right: 10,
    top: 25,
    fontSize: 24,
    color: 'grey',
  },
});
