import {StyleSheet} from 'react-native';
import {fontFamily, fontSize, hp, isIOS, wp} from '../../../utils/helpers';
import {colors} from '../../../utils/colors';

export const style = StyleSheet.create({
  container: {
    marginHorizontal: 17,
    backgroundColor: 'white',
  },

  profileImage: {
    width: '100%',
    height: hp(449),
    borderRadius: 18,
    marginBottom: hp(13),
  },
  imagePlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
  },

  emptyText: {
    marginTop: 20,
    textAlign: 'center',
    color: '#888',
  },
  imageBorderBottomShadow: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    width: '100%',
    height: '40%',
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    marginBottom: hp(13),
  },
  imageBottomDataContainer: {
    position: 'absolute',
    bottom: 35,
    width: '100%',
    marginLeft: wp(21),
  },
  onlineTextBody: {
    width: wp(34.8),
    height: hp(12),
    borderRadius: 5,
    backgroundColor: '#24FF00A8',
    justifyContent: 'center',
  },
  onlineText: {
    color: colors.black,
    fontSize: fontSize(9),
    lineHeight: hp(12),
    textAlign: 'center',
  },
  nameText: {
    color: colors.white,
    fontSize: fontSize(24),
    lineHeight: hp(36),
    fontFamily: fontFamily.poppins700,
    marginTop: 5,
  },
  detailsContainer: {
    flexDirection: 'row',
    marginTop: 3,
  },
  userDetailsTextStyle: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  verticalLineStyle: {
    width: hp(1),
    backgroundColor: colors.gray,
    marginHorizontal: wp(10),
  },
  userDetailsDescriptionContainer: {
    flexDirection: 'row',
  },
  bottomImagesContainer: {
    marginTop: hp(15),
    flexDirection: 'row',
    alignItems: 'center',
  },
  gradientImageBody: {
    width: wp(105),
    height: hp(30),
    resizeMode: 'stretch',
    borderRadius: 50, // Adjust the radius as needed
    overflow: 'hidden', // Ensure rounded corners clip the image
  },
  coupleImageContainer: {
    position: 'absolute',
    left: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  coupleIcon: {
    width: hp(16),
    height: hp(14),
    resizeMode: 'contain',
    tintColor: 'white',
  },
  matchesDataText: {
    color: 'white',
    marginLeft: 9,
    fontSize: fontSize(10),
    lineHeight: hp(15),
    fontFamily: fontFamily.poppins600,
    top: 1,
  },
  bottomImagesSecondContainer: {
    flexDirection: 'row',
    position: 'absolute',
    right: 35,
  },
  counterImageContainer: {
    width: hp(60),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  cameraIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    marginRight: wp(10),
  },
  starImageContainer: {
    width: hp(30),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 50,
  },
  starIcon: {
    width: hp(30),
    height: hp(30),
    resizeMode: 'contain',
  },
  threeDotContainer: {
    width: hp(30),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  threeDotImage: {
    width: 4,
    height: 14,
    tintColor: colors.white,
  },
  staticToastBody: {
    backgroundColor: '#333333',
    borderRadius: 100,
    marginHorizontal: 20,
    width: wp(300),
    height: hp(55),
    justifyContent: 'center',
  },
  staticToastText: {
    color: 'white', // Toast text color
    fontSize: fontSize(16),
    textAlign: 'center',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  cardNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  subPlanContainer: {
    height: 22,
    backgroundColor: 'orange',
    marginLeft: 11,
    borderRadius: 50,
    flexDirection: 'row',
    paddingHorizontal: 7,
  },
  crowIcon: {
    width: 11,
    height: 11,
    tintColor: 'white',
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  planNameText: {
    color: 'white',
    fontSize: fontSize(12),
    fontWeight: 'bold',
    alignSelf: 'center',
    marginLeft: 3,
  },
  threeDotBottomSheetContainer: {
    marginHorizontal: 30,
    marginTop: 20,
  },
  threeDotBottomSheetBody: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  threeDotBottomSheetIcon: {
    width: hp(17),
    height: hp(17),
    resizeMode: 'contain',
    marginRight: hp(22),
  },
  threeDotBottomSheetTittleText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  threeDotBottomSheetContainers: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(20),
  },
  reportBottomSheetContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: hp(24),
    alignItems: 'center',
    marginHorizontal: 17,
  },
  ReportBottomSheetBackButtonContainer: {
    position: 'absolute',
    left: 0,
  },
  RBSBackArrowIcon: {
    width: hp(18),
    height: hp(18),
  },
  BRSTittleText: {
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  RBSUnderLine: {
    width: '100%',
    height: 0.7,
    backgroundColor: '#E7E7E7',
    marginTop: hp(20),
  },
  RBSQuestionText: {
    textAlign: 'center',
    marginTop: hp(15),
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  RBSSubTittleTextContainer: {
    alignItems: 'center',
    marginTop: hp(9),
  },
  RBSSubTittleText: {
    color: '#8F8F8F',
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  RBSSubTittleSubText: {
    color: '#8F8F8F',
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  RBSTextInputContainer: {
    marginTop: hp(28),
    marginHorizontal: 17,
  },
  RBSTextInputBody: {
    borderWidth: 1,
    borderColor: colors.black,
    padding: 10,
    marginBottom: 20,
    borderRadius: 10,
    height: hp(120),
    textAlignVertical: 'top',
  },
  RBSSubmitButtonContainer: {
    width: '100%',
    height: hp(50),
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  RBSSubmitButtonText: {
    color: colors.white,
    marginLeft: hp(20),
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
  },
  RBSReasonText: {
    marginTop: hp(25),
    marginHorizontal: 17,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  RBSSpamTextContainer: {
    marginTop: hp(26),
    marginHorizontal: 17,
  },
  RBSSpamText: {
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  RBSSpamTextBody: {
    marginTop: hp(28),
  },
  RBSSubmitModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  RBSSubmitModalBody: {
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
    width: '85%',
  },
  RBSSubmitModalTittle: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
    textAlign: 'center',
    marginTop: hp(43),
  },
  RBSSubmitModalSubContainer: {
    marginTop: hp(38),
    alignItems: 'center',
  },
  RBSSubmitModalSubTittle: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  RBSSubmitModalSubTittles: {
    textAlign: 'center',
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  RBSSubmitModalOkButton: {
    marginTop: hp(38),
    marginBottom: hp(43),
  },
  RBSSubmitModalOkButtonBody: {
    width: hp(131),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  RBSSubmitModalOkButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  blockModalContainerBody: {
    width: wp(350),
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  blockModalSubTittleText: {
    fontSize: fontSize(16),
    color: colors.black,
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(30),
  },
  blockModalYesButtonBody: {
    width: hp(122),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  blockModalYesText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalNoButtonContainer: {
    width: wp(122),
    height: hp(50),
    borderRadius: 50,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent',
  },
  blockModalNoButtonBody: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  blockModalNoButtonText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalTittleText: {
    fontSize: fontSize(16),
    color: colors.black,
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    marginTop: hp(20),
  },
  receivedShimmerContainer: {
    height: hp(449),
    marginHorizontal: 17,
  },
  receivedShimmerImageBody: {
    width: '100%',
    height: hp(449),
    borderRadius: 10,
    marginBottom: hp(13),
  },
  receivedShimmerImageBodyInside: {
    marginTop: -180,
    marginHorizontal: 17,
  },
  receivedShimmerName: {
    width: 100,
    height: 20,
  },
  receivedShimmerInsideOne: {
    marginTop: 10,
  },
  receivedShimmerData: {
    width: 100,
    height: 5,
  },
  receivedShimmerButtonContainer: {
    marginTop: 50,
    flexDirection: 'row',
  },
  receivedShimmerButton: {
    width: wp(142),
    height: hp(40),
    justifyContent: 'center',
    marginRight: 40,
  },
  noFriendDataContaier: {
    alignItems: 'center',
    marginTop: hp(200),
    justifyContent: 'center',
  },
  noImage: {
    width: hp(44),
    height: hp(44),
    resizeMode: 'contain',
  },
  noFriendText: {
    color: colors.black,
    fontSize: fontSize(18),
    lineHeight: hp(27),
    marginTop: hp(12),
    fontFamily: fontFamily.poppins400,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  modalBodyStyle: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: wp(340),
    height: hp(550),
  },
  modalTittleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(25),
    marginHorizontal: 20,
  },
  tittleTextModal: {
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins500,
    color: colors.black,
  },
  tittleTextNum: {
    color: colors.blue,
    fontSize: fontSize(20),
    lineHeight: hp(30),
    fontFamily: fontFamily.poppins500,
  },
  cancelIconContainer: {
    position: 'absolute',
    right: -5,
    height: hp(25),
    width: hp(25),
    justifyContent: 'center',
    alignItems: 'center',
    top: -15,
    // backgroundColor: '#B0B0B0',
    // borderRadius: 25,
  },
  cancelIcon: {
    width: hp(13),
    height: hp(13),
    // resizeMode: 'contain',
    tintColor: 'black',
  },
  matchImageContainer: {
    marginTop: hp(26),
    flexDirection: 'row',
    alignSelf: 'center',
  },
  firstImageStyle: {
    width: hp(64),
    height: hp(64),
    borderRadius: 50,
    marginRight: -15,
    zIndex: 1,
  },
  secondImageStyle: {
    width: hp(64),
    height: hp(64),
    borderRadius: 50,
  },
  matchNameContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: hp(15),
  },
  coupleIcons: {
    width: hp(16),
    height: hp(14),
    resizeMode: 'contain',
    tintColor: '#8225AF',
    marginRight: wp(10),
  },
  matchName: {
    color: colors.black,
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins500,
  },
  underLineStyle: {
    width: '100%',
    borderWidth: 0.8,
    borderColor: '#EAEAEA',
    marginTop: hp(17),
  },
  modalBodyDescription: {
    color: colors.blue,
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins500,
    textAlign: 'center',
    marginTop: hp(17),
  },
  modalBodyContainer: {
    marginHorizontal: 20,
    marginTop: hp(13),
  },
  tittleTextStyle: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  subTittleUpperContainer: {
    marginTop: hp(10),
  },
  subTittleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  subTittleText: {
    fontSize: fontSize(14),
    lineHeight: hp(22),
    fontFamily: fontFamily.poppins700,
    color: colors.black,
    width: '90%',
  },
  checkIcon: {
    width: hp(18),
    height: hp(18),
    resizeMode: 'contain',
    // tintColor: colors.blue,
  },
  modalBottomNavigationContainer: {
    flex: 1,
    flexDirection: 'row',
    // width: '90%',
    width: '70%',
    position: 'absolute',
    bottom: 25,
    justifyContent: 'space-evenly',
    alignSelf: 'center',
  },
  previousBackIconContainer: {
    width: wp(30),
    alignItems: 'center',
  },
  previousBackIcon: {
    width: hp(12),
    height: hp(24),
    resizeMode: 'contain',
    transform: [{rotate: '180deg'}],
  },
  bottomPagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomPaginationStyle: {
    width: 14,
    height: 14,
    borderRadius: 50,
    marginHorizontal: 10,
  },
  nextIconContainer: {
    width: wp(30),
    alignItems: 'center',
  },
  nextIcon: {
    width: hp(12),
    height: hp(24),
    resizeMode: 'contain',
  },
});
