import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, isIOS, wp} from '../../utils/helpers';

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(14),
  },
  appLogoStyle: {
    width: wp(96),
    height: hp(24),
    marginLeft: wp(17),
    resizeMode: 'contain',
  },
  profileLogoStyle: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
    marginRight: wp(17),
    resizeMode: 'cover',
  },
  headerSubContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(31),
    marginHorizontal: 17,
    alignItems: 'center',
  },
  headerSubTittle: {
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
  },
  backArrowStyle: {
    width: hp(30),
    height: hp(30),
    justifyContent: 'center',
    alignItems: 'center',
  },
  backArrowIcon: {
    width: hp(14),
    height: hp(14),
  },
  headerUnderLine: {
    width: '100%',
    height: hp(1),
    backgroundColor: '#F2F2F2',
    marginTop: hp(12),
  },
  bodyContainer: {
    marginHorizontal: 17,
    marginTop: hp(22),
  },
  bodyTittle: {
    color: '#858585',
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  textInputStyle: {
    width: '100%',
    borderWidth: 1,
    borderColor: colors.black,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
    fontSize: fontSize(18),
    lineHeight: hp(27),
    fontFamily: fontFamily.poppins500,
    height: hp(44),
  },
  bodyUnderLine: {
    width: '100%',
    height: 4,
    backgroundColor: '#F8F8F8',
    marginTop: hp(41),
  },
  bodySubContainer: {
    marginHorizontal: 17,
    marginTop: hp(24),
  },
  bodySubTittle: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins600,
    color: '#0F52BA',
  },
  bodySubTittleSub: {
    fontSize: fontSize(13),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
    marginTop: hp(17),
  },
  idTypeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    borderWidth: 1,
    height: 44,
    borderRadius: 25,
    paddingHorizontal: 20,
    borderColor: '#E5E5E5',
    marginTop: 17,
  },
  selectedIdText: {
    color: 'black',
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  rightArrowContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  rightArrowIcon: {
    width: hp(6),
    height: hp(11),
  },
  bottomSheetTitle: {
    color: 'black',
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    marginTop: hp(24),
    marginBottom: hp(23),
    marginHorizontal: hp(18),
  },
  bottomSheetUnderLine: {
    width: '100%',
    backgroundColor: '#DADADA',
    height: 1,
    marginBottom: hp(23),
  },
  bottomSheetOptionText: {
    color: 'black',
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    marginHorizontal: 18,
  },
  selectImageContainer: {
    width: '100%',
    height: hp(44),
    borderRadius: 50,
    borderWidth: 1.1,
    justifyContent: 'center',
    borderColor: 'transparent',
  },
  selectedImageBody: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
    flexDirection: 'row', // To place text and cancel button horizontally
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  notSelectedImageBody: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  selectedFileText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  selectedImageText: {
    color: colors.black,
    margin: 10,
    fontSize: fontSize(10),
    lineHeight: hp(14),
    fontFamily: fontFamily.poppins400,
    flex: 1,
  },
  cancelContainer: {
    width: hp(18),
    height: hp(18),
    backgroundColor: '#5F6368',
    borderRadius: hp(9), // This ensures the circle is perfectly round
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  cancelTextStyle: {
    color: 'white',
    fontSize: fontSize(10),
    fontFamily: fontFamily.poppins500,
    top: 1,
  },
  applyButtonContainer: {
    position: 'absolute',
    bottom: 20,
    width: '90%',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  applyButtonBody: {
    width: '100%',
    height: hp(44),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  applyButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalBodyContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: '90%',
    alignItems: 'center',
  },
  gradientCircleIcon: {
    width: hp(34),
    height: hp(34),
    resizeMode: 'contain',
    marginTop: hp(49),
    marginBottom: hp(42),
  },
  modalTextStyle: {
    fontSize: fontSize(16),
    textAlign: 'center',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  modalOkButtonContainer: {
    width: hp(158),
    height: hp(44),
    borderRadius: 25,
    marginTop: hp(41),
    marginBottom: hp(55),
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default style;
