import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, wp} from '../../utils/helpers';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainerView: {
    marginHorizontal: wp(17),
    marginTop: hp(14),
  },
  headerContainerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  customerHeaderImage: {
    width: wp(96),
    height: hp(24),
    resizeMode: 'contain',
  },
  profileImageStyle: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
  },
  headingTittleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(31),
  },
  headingCredentialsImageStyle: {
    width: hp(14),
    height: hp(14),
    tintColor: colors.black,
  },
  headingCredentialsText: {
    // marginLeft: wp(12.8),
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
    color: colors.black,
  },
  backButtonContainer: {
    position: 'absolute',
    right: 2,
    width: hp(24),
    height: hp(24),
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonIconStyle: {
    width: hp(14),
    height: hp(14),
  },
  underLineHeaderStyle: {
    width: '100%',
    marginTop: hp(12),
    height: 1,
    backgroundColor: '#E7E7E7',
  },
  submitFunctionContainer: {
    marginHorizontal: wp(17),
    // flex: 1,
    marginTop: hp(13),
  },
  finalSubmitText: {
    color: colors.black,
    fontSize: fontSize(13),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    marginTop: hp(14),
  },
  uploadIdText: {
    color: colors.black,
    fontFamily: fontFamily.poppins500,
    fontSize: fontSize(16),
    lineHeight: hp(24),
  },
  subSubmitTextTittle: {
    color: colors.black,
    fontFamily: fontFamily.poppins400,
    fontSize: fontSize(12),
    lineHeight: hp(18),
    marginTop: hp(11),
  },
  selectedImageContainer: {
    width: '100%',
    height: hp(50),
    borderRadius: 25,
    marginTop: hp(16),
    backgroundColor: '#F7F8FF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
  },
  selectedImageText: {
    color: colors.black,
    fontFamily: fontFamily.poppins400,
    fontSize: fontSize(11),
    lineHeight: hp(16),
  },
  cancelImageContainer: {
    width: hp(18),
    height: hp(18),
    borderRadius: 50,
    backgroundColor: '#5F6368',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: colors.white,
  },
  submitButton: {
    width: '100%',
    height: hp(50),
    marginTop: hp(20),
  },
  bottomSheetContainer: {
    position: 'relative',
    marginTop: 20,
  },
  selectedDocumentTextInput: {
    width: '100%',
    height: hp(45),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 25,
    paddingLeft: 20,
    paddingRight: 50,
    color: 'black',
  },
  dropDownIcon: {
    width: 10,
    height: 6,
    position: 'absolute',
    right: 25,
    top: 20,
    tintColor: 'black',
  },
  textInputContainer: {
    marginHorizontal: 18,
  },
  photoTypeText: {
    color: 'black',
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    marginTop: hp(24),
    marginBottom: hp(23),
  },
  bottomSheetUnderLine: {
    width: '100%',
    borderColor: '#DADADA',
    borderWidth: 0.5,
    marginBottom: hp(23),
  },
  passwordText: {
    color: 'black',
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  bottomSheetText: {
    color: 'black',
    fontSize: fontSize(14),
    lineHeight: hp(28),
    fontFamily: fontFamily.poppins400,
    marginTop: hp(15),
  },
  selectedFileButton: {
    width: '100%',
    height: hp(50),
    marginTop: hp(20),
  },
  secondBodyContainer: {
    marginTop: 16,
    marginHorizontal: 17,
  },
  photoVerifyText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    color: colors.black,
  },
  SubTextTittle: {
    fontSize: fontSize(13),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  verifyTittleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  reviewProgressText: {
    fontSize: fontSize(10),
    lineHeight: hp(15),
    fontFamily: fontFamily.poppins400,
    color: '#9A9999',
    top: 5,
  },
  horizontalLine: {
    width: '100%',
    backgroundColor: '#E7E7E7',
    height: 0.7,
    marginTop: 27,
  },
  kycPictureSubTittle: {
    fontSize: fontSize(12),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  verifyButtonContainer: {
    marginTop: hp(24),
  },
  verifyButtonBody: {
    width: '100%',
    height: 50,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifyButtonText: {
    color: colors.white,
    marginLeft: hp(20),
    textAlign: 'center',
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  verifyButtonIconStyle: {
    width: hp(14),
    height: hp(14),
    tintColor: colors.white,
    marginRight: hp(22.12),
    position: 'absolute',
    right: 0,
    transform: [{rotate: '180deg'}],
    resizeMode: 'contain',
  },
});
