import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, wp} from '../../utils/helpers';

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainerView: {
    marginHorizontal: wp(18),
    marginTop: hp(14),
  },
  headerContainerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  customerHeaderImage: {
    width: wp(96),
    height: hp(24),
    resizeMode: 'contain',
  },
  profileImageStyle: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
  },
  headingTittleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(31),
  },
  headingCredentialsText: {
    // marginLeft: wp(12.8),
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
    color: colors.black,
  },
  backButtonContainer: {
    position: 'absolute',
    right: 2,
    width: hp(24),
    height: hp(24),
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonIconStyle: {
    width: hp(14),
    height: hp(14),
  },
  underLineHeaderStyle: {
    width: '100%',
    marginTop: hp(12),
    height: 1,
    backgroundColor: '#E7E7E7',
  },
  bodyContainer: {
    marginHorizontal: 18,
    marginTop: hp(25),
  },
  bodyTittle: {
    marginBottom: hp(10),
    fontSize: fontSize(14),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: '#909090',
  },
  gradientContainer: {
    borderRadius: 14,
    padding: 20,
    justifyContent: 'center',
    height: hp(101),
  },
  profileTittleStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileText: {
    color: 'white',
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  defaultContainer: {
    backgroundColor: 'white',
    borderRadius: 20,
    width: hp(54),
    height: hp(18),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: hp(11),
  },
  defaultText: {
    fontSize: fontSize(9),
    color: 'black',
    fontFamily: fontFamily.poppins400,
    lineHeight: hp(12),
  },
  descriptionText: {
    color: 'white',
    marginTop: 9,
    fontSize: fontSize(12),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
  },
  checkIcon: {
    position: 'absolute',
    right: 15,
    top: 15,
    width: 20,
    height: 20,
  },
  secondProfileTittle: {
    backgroundColor: '#FAFAFA',
    borderRadius: 14,
    padding: 20,
    justifyContent: 'center',
    height: hp(101),
  },
  secondProfileTittleText: {
    color: 'black',
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  secondDescriptionText: {
    color: '#818181',
    marginTop: 9,
    fontSize: fontSize(12),
    lineHeight: hp(16),
    fontFamily: fontFamily.poppins400,
  },
  moreSettingContainer: {
    marginTop: hp(32),
    marginHorizontal: 18,
  },
  moreSettingText: {
    color: '#909090',
    fontSize: fontSize(14),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
  },
  horizontalLine: {
    width: '100%',
    height: 1.5,
    backgroundColor: '#F2F2F2',
    marginTop: hp(18),
  },
  thirdContainer: {
    marginTop: hp(24),
    marginHorizontal: 18,
  },
  bodyTittleText: {
    fontSize: fontSize(14),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  dataTouchableContainer: {
    marginTop: hp(15),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: hp(30),
  },
  dataTouchableBody: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  dataTouchableBodyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedDataText: {
    color: 'black',
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  anyOneContainer: {
    backgroundColor: '#EAEAEA',
    marginLeft: 7,
    width: hp(115),
    height: hp(20),
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  anyOneText: {
    fontSize: fontSize(11),
    color: 'black',
  },
  rightSideIcon: {
    width: hp(6),
    height: hp(11),
    marginRight: 5,
    resizeMode: 'contain',
  },
  bottomSheetTittle: {
    marginHorizontal: hp(20),
    marginBottom: hp(15),
    marginTop: hp(23),
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
    color: colors.black,
  },
  bottomSheetHorizontalLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#E7E7E7',
  },
  bottomSheetBodyContainer: {
    marginHorizontal: hp(20),
    marginTop: hp(10),
  },
  bottomSheetValueContainer: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  bottomSheetValueBody: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bottomSheetValueText: {
    fontSize: fontSize(16),
    color: colors.black,
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  bottomSheetLabelContainer: {
    backgroundColor: '#EAEAEA',
    marginLeft: 11,
    width: hp(115),
    height: hp(20),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    top: -2,
  },
  bottomSheetLabelText: {
    fontSize: fontSize(11),
    color: 'black',
  },
  horizontalSecondLine: {
    width: '100%',
    height: 1.5,
    backgroundColor: '#F2F2F2',
    marginTop: hp(21),
  },
  saveButtonContainer: {
    flex: 1,
    marginHorizontal: 18,
  },
  saveButtonBody: {
    marginTop: hp(36),
    width: '100%',
    height: hp(50),
    borderRadius: 25,
    justifyContent: 'center',
  },
  saveButtonText: {
    color: colors.white,
    textAlign: 'center',
    fontSize: fontSize(14),
    lineHeight: hp(18),
    fontFamily: fontFamily.poppins400,
  },
});

export default style;
