import {StyleSheet} from 'react-native';
import {colors} from '../../utils/colors';
import {fontFamily, fontSize, hp, isIOS, wp} from '../../utils/helpers';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  centered: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(14),
  },
  customHeaderLogo: {
    width: wp(96),
    height: hp(24),
    marginLeft: wp(17),
    resizeMode: 'contain',
  },
  profileLogoStyle: {
    width: hp(24),
    height: hp(24),
    borderRadius: 50,
    marginRight: wp(17),
    resizeMode: 'cover',
  },
  userStoryContainer: {
    marginTop: hp(15),
    marginHorizontal: wp(17),
    height: hp(60),
  },
  UserDetailsContainer: {
    position: 'absolute',
    bottom: 0,
    width: '90%',
    marginRight: wp(17),
    marginHorizontal: wp(17),
  },
  onlineBodyStyle: {
    width: wp(34),
    height: hp(12),
    borderRadius: 5,
    backgroundColor: '#24FF00A8',
  },
  bodyTextStyle: {
    color: colors.black,
    fontSize: fontSize(9),
    lineHeight: hp(12),
    textAlign: 'center',
  },
  userNameTextStyle: {
    color: colors.white,
    fontSize: fontSize(24),
    lineHeight: hp(36),
    fontFamily: fontFamily.poppins700,
  },
  userDetailsDescriptionContainer: {
    flexDirection: 'row',
  },
  userDetailsTextStyle: {
    color: colors.white,
    fontSize: fontSize(11),
    lineHeight: hp(17),
    fontFamily: fontFamily.poppins400,
    marginRight: wp(2),
  },
  verticalLineStyle: {
    width: hp(1.5),
    height: '90%',
    backgroundColor: colors.gray,
    marginHorizontal: wp(5),
  },
  bottomImageContainer: {
    flexDirection: 'row',
    marginTop: hp(10),
    alignItems: 'center',
  },
  matchesText: {
    fontSize: fontSize(10),
    lineHeight: hp(15),
    fontFamily: fontFamily.poppins600,
    color: colors.white,
  },
  imageBottomShadow: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 150,
  },
  imageBottomContainer: {
    position: 'absolute',
    bottom: 20,
    width: '100%',
  },
  bottomImagesContainer: {
    marginTop: hp(15),
    flexDirection: 'row',
    alignItems: 'center',
  },
  gradientImageContainer: {
    width: wp(105),
    height: hp(30),
    resizeMode: 'stretch',
    borderRadius: 50,
    overflow: 'hidden',
  },
  gradientImageBody: {
    position: 'absolute',
    left: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  coupleImage: {
    width: hp(16),
    height: hp(14),
    resizeMode: 'contain',
    tintColor: 'white',
  },
  percentageText: {
    color: 'white',
    marginLeft: 9,
    fontSize: fontSize(10),
    lineHeight: hp(15),
    fontFamily: fontFamily.poppins600,
    top: 1,
  },
  bottomSecondImagesContainer: {
    flexDirection: 'row',
    position: 'absolute',
    right: -5,
  },
  cameraImageContainer: {
    width: hp(60),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: 10,
  },
  cameraIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    marginRight: wp(10),
  },
  starIconContainer: {
    width: hp(30),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 50,
    marginRight: 10,
  },
  starIcon: {
    width: hp(30),
    height: hp(30),
    resizeMode: 'contain',
  },
  threeDotImageContainer: {
    width: hp(30),
    height: hp(30),
    backgroundColor: '#282727',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  threeDotImage: {
    width: 4,
    height: 14,
    tintColor: colors.white,
  },
  bodyMiddleContainer: {
    marginHorizontal: wp(17),
    marginTop: hp(18),
  },
  BodyContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 15,
    marginTop: 5,
  },
  sendRequestIcon: {
    width: hp(180),
    height: hp(40),
    resizeMode: 'contain',
    marginRight: 20,
  },
  likeIcon: {
    width: hp(63),
    height: hp(40),
    resizeMode: 'contain',
  },
  threeDotBottomSheetContainer: {
    marginHorizontal: 30,
    marginTop: 20,
  },
  threeDotBottomSheetBody: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  threeDotBottomSheetIcon: {
    width: hp(17),
    height: hp(17),
    resizeMode: 'contain',
    marginRight: hp(22),
  },
  threeDotBottomSheetTittleText: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  threeDotBottomSheetContainers: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(20),
    // backgroundColor: 'silver',
  },
  blockModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  blockModalContainerBody: {
    width: wp(350),
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  blockModalTittleText: {
    fontSize: fontSize(16),
    color: colors.black,
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    marginTop: hp(20),
  },
  blockModalSubTittleText: {
    fontSize: fontSize(16),
    color: colors.black,
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(30),
  },
  blockModalYesButtonBody: {
    width: hp(122),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  blockModalYesText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  blockModalNoButtonContainer: {
    width: wp(122),
    height: hp(50),
    borderRadius: 50,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent',
  },
  blockModalNoButtonBody: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  blockModalNoButtonText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  unFriendModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  unFriendModalContainerBody: {
    width: wp(320),
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  unFriendModalTittle: {
    fontSize: fontSize(16),
    color: 'black',
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
    marginTop: hp(30),
    textAlign: 'center',
  },
  unFriendModalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(42),
  },
  unFriendModalYesButtonBody: {
    width: hp(122),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unFriendModalYesButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  unFriendModalNoButtonBodyContainer: {
    width: wp(122),
    height: hp(50),
    borderRadius: 50,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: 'transparent',
  },
  unFriendModalNoButtonBody: {
    borderRadius: 50, // <-- Inner Border Radius
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    margin: isIOS ? 0 : 1,
  },
  unFriendModalNoButtonText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    color: colors.black,
    margin: 10,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
  reportBottomSheetContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: hp(24),
    alignItems: 'center',
    marginHorizontal: 17,
  },
  ReportBottomSheetBackButtonContainer: {
    position: 'absolute',
    left: 0,
  },
  RBSBackArrowIcon: {
    width: hp(18),
    height: hp(18),
  },
  BRSTittleText: {
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  RBSUnderLine: {
    width: '100%',
    height: 0.7,
    backgroundColor: '#E7E7E7',
    marginTop: hp(20),
  },
  RBSQuestionText: {
    textAlign: 'center',
    marginTop: hp(15),
    color: colors.black,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins500,
  },
  RBSSubTittleTextContainer: {
    alignItems: 'center',
    marginTop: hp(9),
  },
  RBSSubTittleText: {
    color: '#8F8F8F',
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  RBSSubTittleSubText: {
    color: '#8F8F8F',
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  RBSTextInputContainer: {
    marginTop: hp(28),
    marginHorizontal: 17,
  },
  RBSTextInputBody: {
    borderWidth: 1,
    borderColor: colors.black,
    padding: 10,
    marginBottom: 20,
    borderRadius: 10,
    height: hp(120),
    textAlignVertical: 'top',
  },
  RBSSubmitButtonContainer: {
    width: '100%',
    height: hp(50),
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  RBSSubmitButtonText: {
    color: colors.white,
    marginLeft: hp(20),
    fontSize: fontSize(16),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins500,
  },
  RBSReasonText: {
    marginTop: hp(25),
    marginHorizontal: 17,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  RBSSpamTextContainer: {
    marginTop: hp(26),
    marginHorizontal: 17,
  },
  RBSSpamTextBody: {
    marginTop: hp(28),
  },
  RBSSpamText: {
    color: colors.black,
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
  },
  RBSSubmitModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  RBSSubmitModalBody: {
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
    width: '85%',
  },
  RBSSubmitModalTittle: {
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins600,
    color: colors.black,
    textAlign: 'center',
    marginTop: hp(43),
  },
  RBSSubmitModalSubContainer: {
    marginTop: hp(38),
    alignItems: 'center',
  },
  RBSSubmitModalSubTittle: {
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  RBSSubmitModalSubTittles: {
    textAlign: 'center',
    fontSize: fontSize(14),
    lineHeight: hp(21),
    fontFamily: fontFamily.poppins400,
    color: colors.black,
  },
  RBSSubmitModalOkButton: {
    marginTop: hp(38),
    marginBottom: hp(43),
  },
  RBSSubmitModalOkButtonBody: {
    width: hp(131),
    height: hp(50),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  RBSSubmitModalOkButtonText: {
    color: colors.white,
    fontSize: fontSize(16),
    lineHeight: hp(24),
    fontFamily: fontFamily.poppins400,
  },
});
